// ═══════════════════════════════════════════════════════════
// KALA DARSHAN — Complete Jyotish Encyclopedia Data
// ═══════════════════════════════════════════════════════════

export const grahas = [
  {
    slug: "surya",
    name: "Surya",
    sanskrit: "सूर्य",
    english: "The Sun",
    symbol: "☉",
    dashaYears: 6,
    color: "#f0c040",
    owns: ["Leo (Simha)"],
    exaltation: "Aries 10°",
    debilitation: "Libra 10°",
    mooltrikona: "Leo 0–20°",
    friends: ["Moon","Mars","Jupiter"],
    enemies: ["Venus","Saturn"],
    neutral: ["Mercury"],
    kala: "Soul (Atma)",
    domains: ["Soul","Authority","Father","Government","Vitality","Ego","Spine","Eyes","Heart"],
    guna: "Sattvic",
    element: "Fire",
    direction: "East",
    day: "Sunday",
    gem: "Ruby",
    metal: "Gold",
    mantra: "Om Hraam Hreem Hroum Sah Suryaya Namah",
    shortDescription: "The royal luminary. Surya is the Atma — the soul itself — expressed in the chart. He illuminates but also burns. What is too close to Surya is combusted: it loses its independent voice and merges with the solar principle.",
    encyclopediaEntry: {
      nature: "Surya is the only graha that is classified as a permanent malefic for worldly purposes yet is the most benefic from the soul's perspective. This paradox is central to understanding his placement in any chart. He destroys ego-structures (malefic action) to reveal the Atma beneath them (benefic result). The house Surya occupies becomes the arena where the ego is simultaneously built and periodically burned away.",
      combustion: "Combustion (Astangata) occurs when a planet comes within Surya's orb — typically 6° for most planets, though Mercury can be cazimi (within 1°) and gain exceptional strength. A combust planet loses the ability to independently express its significations: it becomes subordinate to Surya's agenda. Combust Venus produces a native who must earn beauty and love through solar means — through achievement and recognition — rather than receiving them freely. Combust Mercury creates the Budha-Aditya Yoga paradox: combustion and exceptional solar intelligence simultaneously.",
      houseEffects: "Surya in the 1st: The self shines, authority is constitutional. Tendency toward pride that needs tempering. In the 4th: The father's influence on the home, or the father's absence from it, is defining. In the 7th: Combusts the 7th house significations — partners are strong-willed or the native's solar force overwhelms partnerships. In the 10th (exalted direction): The most powerful placement for career — Surya in the 10th in Aries approaches maximum strength. In the 12th: The 'hidden sun' — the soul that operates from behind the veil, producing mystics and those who illuminate others while remaining unseen.",
      transit: "Surya's transit takes 1 month per sign — 1 year for the full zodiac. Surya transiting the natal Moon (called Chandra-Surya yoga in transit) marks important emotional clarification periods. Surya's transit over the natal lagna (birthday period) is the solar return — a reset of the annual cycle. Surya transiting the 8th from the natal Moon (Ashtama Surya) is classically considered challenging for health and authority.",
      secretKnowledge: "What almost no contemporary Jyotish teacher discusses: Surya is the graha of Dharana — the yogic practice of concentration. His combustion of other planets is not destruction but absorption into a higher principle of focus. A chart with multiple combustions often produces a native capable of extraordinary single-pointed concentration — but at the cost of the diversified expression those planets would otherwise provide. The question for such a native is not 'how do I strengthen my combust planets' but 'what is Surya focusing me toward?'",
    },
  },
  {
    slug: "chandra",
    name: "Chandra",
    sanskrit: "चन्द्र",
    english: "The Moon",
    symbol: "☽",
    dashaYears: 10,
    color: "#c8e0f8",
    owns: ["Cancer (Karka)"],
    exaltation: "Taurus 3°",
    debilitation: "Scorpio 3°",
    mooltrikona: "Taurus 4–20°",
    friends: ["Sun","Mercury"],
    enemies: ["None (the Moon has no permanent enemies)"],
    neutral: ["Mars","Jupiter","Venus","Saturn"],
    kala: "Mind (Manas)",
    domains: ["Mind","Mother","Emotions","Public","Fluids","Fertility","Travel","Left Eye","Breast"],
    guna: "Sattvic",
    element: "Water",
    direction: "Northwest",
    day: "Monday",
    gem: "Pearl (Moti)",
    metal: "Silver",
    mantra: "Om Shraam Shreem Shroum Sah Chandraya Namah",
    shortDescription: "The mirror of consciousness. Chandra reflects — it generates no light of its own. Whatever Chandra touches in the chart, the manas (mind) makes personal, emotional, and tidal. The Moon's phase at birth and its nakshatra are the two most personally sensitive data points in any chart.",
    encyclopediaEntry: {
      nature: "Chandra is the only graha that changes shape visibly — waxing and waning through its cycle. This is not incidental to its nature; it is its nature. The Moon rules the tidal quality of mind — the way consciousness ebbs and flows, amplifies and recedes, responds to invisible gravitational pulls. A strong Chandra (bright, waxing, well-aspected, in own sign or exaltation) produces a steady, receptive, empathetic mind. A weak Chandra (dark, waning, afflicted, debilitated) produces a mind that struggles with consistency, emotional regulation, and the boundary between self and other.",
      phases: "The Moon's phase at birth (Paksha Bala) is one of the six types of strength (Shadbala) and is often overlooked in modern practice. A native born in Shukla Paksha (waxing fortnight) has a naturally expanding Moon — the mind grows, accumulates, and builds through the lifetime. A native born in Krishna Paksha (waning fortnight) has a contracting Moon — the mind's path is through subtraction, refinement, and eventually transcendence. This is not superior or inferior; it is a different direction of motion through consciousness.",
      janmaNakshatra: "The Janma Nakshatra — the nakshatra occupied by the Moon at birth — is the single most sensitive point in the entire chart. Transits over the Janma Nakshatra produce visceral, immediate responses regardless of the transiting planet's nature. Jupiter transiting Janma Nakshatra produces expansion and grace. Saturn transiting it produces the heaviest form of his teaching. This is the mechanism behind Sade Sati's intensity: Saturn moves through the sign before, the sign of, and the sign after the natal Moon — spending approximately 7.5 years in this most sensitive zone.",
      secretKnowledge: "The concept of Manasa Graha (the mind-planet) extends beyond individual psychology into collective consciousness. When multiple Jyotishis observe the same transit of Chandra over a sensitive natal point and note collective emotional weather — shared anxiety, shared optimism, shared grief — they are observing the Moon's function as the primary mediator between the individual manas and the collective field of consciousness. The Moon is the antenna. Strong Moon = strong reception of collective field. Weak Moon = static, distortion, confusion between one's own feelings and the feelings absorbed from the field.",
    },
  },
  {
    slug: "mangala",
    name: "Mangala",
    sanskrit: "मङ्गल",
    english: "Mars",
    symbol: "♂",
    dashaYears: 7,
    color: "#c84830",
    owns: ["Aries (Mesha)","Scorpio (Vrischika)"],
    exaltation: "Capricorn 28°",
    debilitation: "Cancer 28°",
    mooltrikona: "Aries 0–12°",
    friends: ["Sun","Moon","Jupiter"],
    enemies: ["Mercury","Saturn"],
    neutral: ["Venus"],
    kala: "Courage (Parakrama)",
    domains: ["Courage","Action","Siblings","Land","Military","Surgery","Accidents","Blood","Desire"],
    guna: "Tamasic",
    element: "Fire",
    direction: "South",
    day: "Tuesday",
    gem: "Red Coral (Moonga)",
    metal: "Copper",
    mantra: "Om Kraam Kreem Kroum Sah Bhaumaya Namah",
    shortDescription: "The warrior. Mars does not deliberate — he acts. His debilitation in Cancer creates the most psychologically complex Mars: a warrior forced to fight through feeling rather than force, whose courage must emerge from emotional authenticity rather than aggression.",
    encyclopediaEntry: {
      nature: "Mangala rules the capacity to cut through — to execute, to begin, to fight for what matters. His two signs reveal his dual nature: Aries is the direct, initiating, self-focused Mars; Scorpio is the investigative, strategic, other-focused Mars who uses force surgically rather than openly. The native with a strong Mars does not wait for permission. The native with a weak or afflicted Mars either overcompensates (aggression) or undercompensates (chronic passivity and resentment).",
      kujaDoshaDebate: "Kuja Dosha (Mangala Dosha) — Mars in the 1st, 4th, 7th, 8th, or 12th house — is one of the most misunderstood concepts in popular Jyotish. The dosha creates intensity and potential volatility in the house it occupies, but the severity depends entirely on Mars's dignity (own sign, exalted, or debilitated), its aspects, the sign involved, and the overall chart context. A Kuja Dosha with Mars in own sign Aries in the 7th is completely different from Mars debilitated in Cancer in the 7th. The blanket 'Kuja Dosha = difficult marriage' teaching strips away the contextual intelligence that makes Jyotish precise.",
      debilitation: "Mars's debilitation in Cancer is the most instructive example of a graha outside its natural terrain. Cancer is ruled by the Moon — watery, emotional, receptive, maternal. Mars is fiery, aggressive, outward-moving. In Cancer, Mars must learn to act through feeling — courage expressed as emotional authenticity, conflict transformed into self-protective boundaries rather than external aggression. When Neecha Bhanga (cancellation) occurs — when the Moon (Cancer's ruler) is in a kendra from the lagna or Moon — the debilitated Mars produces results paradoxically stronger than simple dignity. The fall and recovery create depth.",
      secretKnowledge: "Mangala's rulership of the 8th house (Scorpio) connects him to the Ashtama Bhava's most hidden function: the capacity for radical transformation through surrender. A Mars that has learned to yield — not from weakness but from strategic wisdom — is the most powerful Mars of all. This is the teaching of Scorpio Mars versus Aries Mars: the latter fights; the former waits, observes, and strikes with precision when the moment is inevitable. The Scorpionic function of Mars is what makes surgeons, researchers, occultists, and investigators: the warrior who has learned to move through the invisible world.",
    },
  },
  {
    slug: "budha",
    name: "Budha",
    sanskrit: "बुध",
    english: "Mercury",
    symbol: "☿",
    dashaYears: 17,
    color: "#60c880",
    owns: ["Gemini (Mithuna)","Virgo (Kanya)"],
    exaltation: "Virgo 15°",
    debilitation: "Pisces 15°",
    mooltrikona: "Virgo 16–20°",
    friends: ["Sun","Venus"],
    enemies: ["Moon"],
    neutral: ["Mars","Jupiter","Saturn"],
    kala: "Discrimination (Viveka)",
    domains: ["Intellect","Speech","Trade","Skin","Nervous System","Writing","Mathematics","Commerce","Humor"],
    guna: "Rajasic",
    element: "Earth/Air",
    direction: "North",
    day: "Wednesday",
    gem: "Emerald (Panna)",
    metal: "Brass",
    mantra: "Om Braam Breem Broum Sah Budhaya Namah",
    shortDescription: "The discriminator. Budha governs Viveka — the capacity to distinguish, classify, and communicate precisely. He is the planet of the nervous system: both the body's neural network and the mind's discriminating intelligence.",
    encyclopediaEntry: {
      nature: "Mercury is the only planet that is exalted in the same sign it rules (Virgo). This tells us something essential about his nature: Mercury's highest expression is discrimination itself — the precise analysis and categorization of reality. In Virgo, Mercury reaches the pinnacle of his analytical function. In Pisces (debilitation), Mercury must operate in the sign of dissolution and imagination — the capacity to think dissolves into feeling and intuition, which is why Pisces Mercury often produces poets, mystics, and artists rather than accountants and analysts.",
      combustion: "Mercury's combustion by the Sun creates the Budha-Aditya Yoga paradox. Mercury is combust whenever within 14° of the Sun — yet because Mercury is always relatively close to the Sun (never more than 28° away), a large percentage of charts have Mercury combust. The traditional view is that combustion weakens Mercury. The deeper view: Mercury combust is Mercury so saturated with solar intelligence that it transcends the ordinary discriminating function and becomes something closer to direct solar knowing — intuitive, fast, comprehensive rather than linear.",
      dualNature: "Mercury's two signs reveal a dual function: Gemini Mercury is the communicating, connecting, networking Mercury — the journalist, the trader, the conversationalist. Virgo Mercury is the analyzing, refining, perfecting Mercury — the craftsman, the healer, the critic. The most precise Mercury natives often have Mercury in Virgo with strong 3rd and 6th house connections: they communicate through craft, through precise service, through the perfection of a skill.",
      secretKnowledge: "The concept rarely discussed: Mercury as Jyotishkarana — the natural karaka (significator) of Jyotish itself. The capacity to read a chart — to see the patterns, discriminate between influences, articulate the timing — is a Mercury function. A strong Mercury in a Jyotishi's chart is not an accident. More importantly: the practice of Jyotish develops Mercury. Sustained engagement with precise symbolic language rewires the discriminating intelligence, making it sharper, faster, more capable of holding multiple simultaneous patterns. Jyotish is both a system of knowledge and a sadhana that strengthens the planet that governs knowledge.",
    },
  },
  {
    slug: "guru",
    name: "Guru",
    sanskrit: "गुरु",
    english: "Jupiter",
    symbol: "♃",
    dashaYears: 16,
    color: "#e8c060",
    owns: ["Sagittarius (Dhanu)","Pisces (Meena)"],
    exaltation: "Cancer 5°",
    debilitation: "Capricorn 5°",
    mooltrikona: "Sagittarius 0–10°",
    friends: ["Sun","Moon","Mars"],
    enemies: ["Mercury","Venus"],
    neutral: ["Saturn"],
    kala: "Wisdom (Jnana)",
    domains: ["Wisdom","Dharma","Children","Husband (female charts)","Teacher","Liver","Fat","Wealth","Philosophy"],
    guna: "Sattvic",
    element: "Ether (Akasha)",
    direction: "Northeast",
    day: "Thursday",
    gem: "Yellow Sapphire (Pukhraj)",
    metal: "Gold",
    mantra: "Om Graam Greem Groum Sah Gurave Namah",
    shortDescription: "The bridge between human effort and divine grace. Guru expands, protects, and elevates wherever he aspects. He is the planet of Dharma — the right way of living that is simultaneously one's deepest nature.",
    encyclopediaEntry: {
      nature: "Jupiter's exaltation in Cancer — the Moon's own sign — is deeply instructive. The highest expression of wisdom is not in Sagittarius (his own sign of philosophy) but in Cancer — the sign of nurturing, emotional receptivity, and deep feeling. True wisdom is not intellectual but compassionate. It is the wisdom that arises when one has felt the full weight of existence and responded with care rather than judgment. Jupiter in Cancer produces the teacher whose knowledge is embodied rather than merely intellectualized.",
      guruChandala: "Guru-Chandala Yoga forms when Jupiter is conjunct Rahu (or sometimes Ketu). In popular Jyotish, this is treated as a defiling of Jupiter's purity by Rahu's shadow. The deeper reading: Rahu expands Jupiter's reach beyond conventional dharma. Guru-Chandala produces teachers, philosophers, and wisdom-keepers who operate outside traditional structures — unorthodox in method but often producing results the orthodox cannot. The 'pollution' is actually unconventionality. The yoga produces worldly wisdom that Rahu delivers to contexts Jupiter alone would never enter.",
      aspectsTeaching: "Jupiter's 5th and 9th aspects (in addition to the standard 7th) are among the most important in Jyotish. The 5th aspect lands on the house of intelligence and creativity; the 9th aspect lands on the house of dharma and grace. Wherever Jupiter's 5th aspect falls, he irrigates creative intelligence. Wherever his 9th aspect falls, he delivers dharmic blessing. A Jupiter in the 5th house aspects the 9th (blessing of dharma), 11th (blessing of gains), and 1st (blessing of the self) — this configuration is considered among the most fortunate possible.",
      secretKnowledge: "The rarely discussed Guru Tattva — the principle of the inner teacher. Jupiter's placement in the chart shows not just where external teachers and wisdom enter the life, but where the native's inner teacher is most alive. A Jupiter in the 12th house in apparent weakness is actually the guru operating in solitude, in dreams, in the invisible worlds — the native's wisdom comes from contemplative sources that others cannot access or verify. This is why some of the most genuinely wise people have Jupiter in the 12th: the teaching comes from Patala itself.",
    },
  },
  {
    slug: "shukra",
    name: "Shukra",
    sanskrit: "शुक्र",
    english: "Venus",
    symbol: "♀",
    dashaYears: 20,
    color: "#e0a868",
    owns: ["Taurus (Vrishabha)","Libra (Tula)"],
    exaltation: "Pisces 27°",
    debilitation: "Virgo 27°",
    mooltrikona: "Libra 0–15°",
    friends: ["Saturn","Mercury"],
    enemies: ["Sun","Moon"],
    neutral: ["Mars","Jupiter"],
    kala: "Desire (Kama)",
    domains: ["Love","Beauty","Wife (male charts)","Vehicles","Art","Luxury","Semen","Kidneys","Pleasure"],
    guna: "Rajasic",
    element: "Water",
    direction: "Southeast",
    day: "Friday",
    gem: "Diamond (Heera)",
    metal: "Silver",
    mantra: "Om Draam Dreem Droum Sah Shukraya Namah",
    shortDescription: "The planet of refined desire and earthly sweetness. Shukra's exaltation in Pisces — the sign of dissolution and transcendence — reveals his deepest nature: the highest Venus transcends personal desire into universal love and artistic devotion.",
    encyclopediaEntry: {
      nature: "Venus is the Guru of the Asuras — the preceptor of the non-divine, the teacher who descended into the world of form and sensation in order to guide consciousness through embodied experience rather than transcendence of it. This is a profound teaching: where Jupiter guides through dharma and wisdom (the divine path), Venus guides through beauty, pleasure, and refined desire (the human path). Both lead to the same destination. Jupiter is the shortcut; Venus is the scenic route.",
      retrograde: "Venus retrograde in the natal chart (Venus Rx) is one of the most significant and misunderstood placements. The Rx symbol is not weakness — it is internalization. Venus Rx turns the pleasure principle inward. The native does not receive beauty and love freely from the world; they must excavate, earn, or encounter sweetness through unusual, unexpected, or backward paths. Venus Rx in the 4th house (own sign Libra) means the inner sanctuary of the heart holds the sweetness — it is there, fully present, but requires a different key than ordinary reaching.",
      dashaEffect: "Venus Mahadasha is the longest at 20 years — a full generation of Venusian expression. What the native experiences depends entirely on Venus's natal condition: its sign, house, aspects, and retrograde status. Venus Dasha in a strong Venus chart produces wealth, relationships, artistic achievement, vehicles, and luxurious circumstances. Venus Dasha with a weak or afflicted Venus produces the lessons of those same domains: the teaching of what one truly values versus what one thought one desired. Both are Venus.",
      secretKnowledge: "Shukra Niti — Venus's political and strategic wisdom — is a dimension of Venus almost never discussed in modern Jyotish. Where Jupiter teaches dharma through wisdom and grace, Venus teaches through charm, strategy, and the understanding of desire in others. The Shukraniti (Venus's political treatise, parallel to Chanakya's Arthashastra) reveals Venus as the planet of sophisticated social and political intelligence. A strong Venus in the 10th or 11th house does not merely produce luxury — it produces the capacity to navigate complex social systems with ease, turning desire itself into a tool of worldly power.",
    },
  },
  {
    slug: "shani",
    name: "Shani",
    sanskrit: "शनि",
    english: "Saturn",
    symbol: "♄",
    dashaYears: 19,
    color: "#6880a8",
    owns: ["Capricorn (Makara)","Aquarius (Kumbha)"],
    exaltation: "Libra 20°",
    debilitation: "Aries 20°",
    mooltrikona: "Aquarius 0–20°",
    friends: ["Mercury","Venus"],
    enemies: ["Sun","Moon","Mars"],
    neutral: ["Jupiter"],
    kala: "Time (Kala)",
    domains: ["Karma","Time","Discipline","Longevity","Servants","Masses","Bones","Teeth","Oil"],
    guna: "Tamasic",
    element: "Air",
    direction: "West",
    day: "Saturday",
    gem: "Blue Sapphire (Neelam)",
    metal: "Iron",
    mantra: "Om Praam Preem Proum Sah Shanaischaraya Namah",
    shortDescription: "Kala's agent. Saturn does not punish — he crystallizes. He is the force of inevitable consequence, the planet that makes things permanent. His dasha is not a period of suffering but of irreversible solidification.",
    encyclopediaEntry: {
      nature: "Saturn's exaltation in Libra — the sign of balance, justice, and relationship — is the key to understanding his deepest function. Saturn at his highest is not restriction but perfect equity: the cosmic principle that ensures every action produces its precise consequence, no more and no less. Saturn in Libra is the just judge, the impartial weigher of deeds. His debilitation in Aries reveals the shadow: Saturn without balance becomes pure restriction, blocking initiative without providing structure.",
      sadeSati: "Sade Sati — Saturn's 7.5-year transit through the three signs surrounding the natal Moon — is simultaneously the most feared and most misunderstood transit in Jyotish. The three phases have distinct qualities. Phase 1 (Saturn in the sign before natal Moon): external circumstances change, the environment shifts, the ground beneath the native becomes unstable. Phase 2 (Saturn transiting natal Moon directly): the mind itself is the terrain — emotional weight, reality-testing, facing what has been avoided. Phase 3 (Saturn in sign after natal Moon): integration, the building of what the previous phases cleared space for. The native who understands Sade Sati as a 7.5-year construction project — clearing old foundations before laying new ones — experiences it completely differently from one who experiences it as punishment.",
      kalapurusha: "Saturn as Kala Purusha — the embodiment of cosmic time — is the teaching that most astrology traditions gesture toward but few articulate precisely. The other planets work in Samaya (sequential time) — they create events, trigger experiences, open and close windows. Saturn works in Kala (depth-time) — he builds the conditions that make events inevitable before they become visible. This is why Saturn's results always feel 'already decided' when they arrive: because they were, long before the event appeared in Bhuloka.",
      secretKnowledge: "Saturn's rulership of Aquarius — the sign of collective humanity, technology, and unconventional systems — reveals a dimension of Saturn that pure 'karma and restriction' frameworks miss: Saturn is the planet of institutions, systems, and structures that serve the many rather than the few. A strong Aquarius Saturn in the chart produces the native who builds lasting structures for collective use — enterprises, systems, knowledge frameworks — that outlive the individual builder. This is Saturn's highest worldly expression: the construction of something permanent that serves those who come after.",
    },
  },
  {
    slug: "rahu",
    name: "Rahu",
    sanskrit: "राहु",
    english: "North Node",
    symbol: "☊",
    dashaYears: 18,
    color: "#9060b0",
    owns: ["Co-ruler of Aquarius (per some traditions)"],
    exaltation: "Taurus (per Parashara) / Gemini (per some traditions)",
    debilitation: "Scorpio / Sagittarius",
    mooltrikona: "Gemini",
    friends: ["Venus","Saturn","Mercury"],
    enemies: ["Sun","Moon"],
    neutral: ["Jupiter","Mars"],
    kala: "Illusion (Maya)",
    domains: ["Obsession","Foreign Elements","Technology","Poisons","Unconventional Paths","Amplification","Mass Media","Epidemics"],
    guna: "Tamasic",
    element: "Air",
    direction: "Southwest",
    day: "Saturday (shares with Saturn)",
    gem: "Hessonite Garnet (Gomed)",
    metal: "Lead",
    mantra: "Om Bhram Bhreem Bhroum Sah Rahave Namah",
    shortDescription: "The amplifier without discrimination. Rahu is the head without a body — he consumes endlessly but cannot be satisfied. He grants what the soul craves at maximum intensity, teaching through the exhaustion of desire rather than its transcendence.",
    encyclopediaEntry: {
      nature: "Rahu and Ketu are not planets in the astronomical sense — they are the intersection points of the Sun's and Moon's orbital planes: the north and south nodes. They are shadow planets (Chaya Grahas) — they have no physical form, no light of their own, yet they produce eclipses: the temporary swallowing of the greatest lights. This function — the capacity to eclipse, to temporarily occlude consciousness — is their core astrological meaning.",
      rahuKalapurusha: "Where Saturn is Kala Purusha (lord of time), Rahu is Maya Purusha (lord of illusion). He amplifies Prakriti — the manifest field — to such intensity that the native loses sight of Purusha entirely. Rahu's greatest gift is precisely this: by taking the native to the absolute limit of worldly experience and desire, he eventually creates the conditions for Ketu's liberation. The Rahu-Ketu axis in the chart is the axis of karma's direction of travel in this lifetime.",
      axisTeaching: "The Rahu-Ketu axis is always opposite — they occupy signs 180° apart. The house Rahu occupies shows where the soul is reaching in this lifetime: the unfamiliar territory, the direction of growth, the arena of obsessive engagement. The house Ketu occupies shows what the soul has mastered in previous lifetimes: it comes easily, produces some indifference, and eventually points toward liberation. The mistake is to avoid Rahu's house (dismissing it as 'too worldly') or to cling to Ketu's house (remaining in what is already known). The evolutionary movement of the soul in this lifetime runs from Ketu toward Rahu.",
      secretKnowledge: "Rahu's rulership of Shatabhisha nakshatra (the nakshatra of Varuna and the hidden ocean) reveals his connection to the healing arts — specifically those forms of healing that operate outside conventional frameworks. Rahu in connection with Shatabhisha produces the unconventional healer, the one who works with what cannot be seen or measured. The '100 physicians' of Shatabhisha are the 100 stars of Rahu's nakshatra — the hidden multitude of healing forces that Varuna commands from beneath the surface of the visible world.",
    },
  },
  {
    slug: "ketu",
    name: "Ketu",
    sanskrit: "केतु",
    english: "South Node",
    symbol: "☋",
    dashaYears: 7,
    color: "#b06840",
    owns: ["Co-ruler of Scorpio (per some traditions)"],
    exaltation: "Scorpio / Sagittarius",
    debilitation: "Taurus / Gemini",
    mooltrikona: "Sagittarius",
    friends: ["Mars","Venus","Saturn"],
    enemies: ["Sun","Moon"],
    neutral: ["Mercury","Jupiter"],
    kala: "Liberation (Moksha)",
    domains: ["Liberation","Past Lives","Dissolution","Spirituality","Sudden Events","Accidents","Moksha","Fire","Occult"],
    guna: "Tamasic",
    element: "Fire",
    direction: "South",
    day: "Tuesday (shares with Mars)",
    gem: "Cat's Eye (Lehsunia)",
    metal: "Iron",
    mantra: "Om Straam Streem Stroum Sah Ketave Namah",
    shortDescription: "The body without a head — the planetary principle that acts without desire, that moves without agenda, that dissolves without attachment. Ketu is the most spiritually elevated of all grahas precisely because he has already exhausted the desire that drives all the others.",
    encyclopediaEntry: {
      nature: "Ketu is liberation made planetary. He is not malefic in any conventional sense — he is simply operating at a frequency that the ego finds threatening. Where every other planet seeks to build, accumulate, and express, Ketu dissolves, releases, and makes transparent. His periods feel like loss. They are actually clarification: the removal of what was never truly one's own.",
      ketuLiberation: "The Moksha Karaka function of Ketu is the most important and least understood dimension of this graha. Ketu placed in the 12th house, or aspecting the 12th lord, or in connection with Pisces or Neptune (Western synthesis) — these configurations produce the native for whom liberation is not a concept but a lived direction of travel. Ketu in the 5th house dissolves ego-attachment to creativity and children: the native creates without claiming, parents without owning. This is agami karma at its finest — action without the seed of future bondage.",
      ketuSaturnAntardasha: "The Saturn-Ketu antardasha (within Saturn Mahadasha) is among the most intense sub-periods in the entire 120-year cycle. Saturn crystallizes; Ketu dissolves. These two forces operate simultaneously and in apparent contradiction. The result: whatever was not truly crystallized — whatever was held by inertia, habit, or false stability rather than genuine structure — is dissolved by Ketu. What remains after this process is what was truly solid. The period feels like loss and stagnation. It is maximum purification of the crystallization process.",
      secretKnowledge: "Ketu's connection to past-life mastery is perhaps the most practically useful dimension for the student of Jyotish. The house and sign where Ketu sits represents a domain where the native has already achieved significant mastery in previous incarnations. The mastery creates two effects: (1) The domain comes naturally but doesn't feel like an achievement, so it may be undervalued. (2) The domain eventually loses its grip on the native — Ketu's attachment-dissolving function ensures the native cannot remain permanently satisfied there. The evolutionary instruction: use the mastery of Ketu's house as a foundation, but build the new work in Rahu's house.",
    },
  },
];

export const nakshatras = [
  { num: 1, name: "Ashwini", sanskrit: "अश्विनी", ruler: "Ketu", deity: "Ashwini Kumaras", symbol: "Horse's Head", guna: "Rajas", motivation: "Dharma", degrees: "Aries 0–13°20'", shortDesc: "The healer twins. Instantaneous healing, speed, and initiatory force. The nakshatra that begins all cycles — the first breath of the cosmos into form.", body: "The two cosmic physicians who arrive before the dawn, healing what others cannot reach. Ashwini's energy is the fastest in the zodiac — it acts before thinking, heals before understanding, arrives before being called." },
  { num: 2, name: "Bharani", sanskrit: "भरणी", ruler: "Venus", deity: "Yama", symbol: "Yoni", guna: "Rajas", motivation: "Artha", degrees: "Aries 13°20'–26°40'", shortDesc: "The bearer of what must be born and what must die. Bharani holds the extremes of creation and destruction in the same womb.", body: "Yama — the lord of death — governs the gate between worlds. Bharani is not death-obsessed but death-wise: those born under this nakshatra often have an unusual ease with the terminal, the transformational, and the taboo." },
  { num: 3, name: "Krittika", sanskrit: "कृत्तिका", ruler: "Sun", deity: "Agni", symbol: "Razor/Flame", guna: "Rajas", motivation: "Kama", degrees: "Aries 26°40'–Taurus 10°", shortDesc: "The Pleiades. Agni's razor — the sacred fire that purifies by burning away impurity. Sharp, direct, intolerant of falseness.", body: "Krittika cuts. The razor-nakshatra does not hedge, soften, or wait. Its natives speak truth regardless of comfort — which makes them extraordinary teachers and terrifying critics." },
  { num: 4, name: "Rohini", sanskrit: "रोहिणी", ruler: "Moon", deity: "Brahma", symbol: "Chariot", guna: "Rajas", motivation: "Moksha", degrees: "Taurus 10–23°20'", shortDesc: "The most beloved of the Moon's stations. Fertility, creation, sensual abundance. Brahma chose Rohini for the act of cosmic creation.", body: "The Moon's favorite nakshatra — the lunar energy is most fully itself in Rohini. Nourishing, creative, deeply embodied. The capacity for beauty-making at its most elemental." },
  { num: 5, name: "Mrigashira", sanskrit: "मृगशिरा", ruler: "Mars", deity: "Soma", symbol: "Deer's Head", guna: "Tamas", motivation: "Moksha", degrees: "Taurus 23°20'–Gemini 6°40'", shortDesc: "The eternal seeker. The deer that searches the forest without arriving. The joy of the search is itself the gift.", body: "Mrigashira natives are perpetually curious — they move through life collecting experiences, impressions, knowledge, never fully settling. The gift: inexhaustible interest. The shadow: restlessness that mistakes motion for progress." },
  { num: 6, name: "Ardra", sanskrit: "आर्द्रा", ruler: "Rahu", deity: "Rudra", symbol: "Teardrop", guna: "Tamas", motivation: "Kama", degrees: "Gemini 6°40'–20°", shortDesc: "The moist one. Rudra's storm before the clearing. The creative destruction that makes renewal possible.", body: "Ardra is the nakshatra of creative destruction — the storm that must come before clarity. Rudra weeps because he understands the cost of transformation. Ardra natives often carry a quality of tender brutality: they break what must be broken with deep compassion for the breaking." },
  { num: 7, name: "Punarvasu", sanskrit: "पुनर्वसु", ruler: "Jupiter", deity: "Aditi", symbol: "Bow & Quiver", guna: "Sattva", motivation: "Artha", degrees: "Gemini 20°–Cancer 3°20'", shortDesc: "Return to light. Aditi — the boundless, inexhaustible mother — restores what was lost. The nakshatra of renewal and re-emergence.", body: "Punarvasu means 'return of the good light.' After Ardra's storm, Punarvasu brings restoration. Jupiter here produces the teacher who returns again and again — who never finally gives up on the student, the project, the truth." },
  { num: 8, name: "Pushya", sanskrit: "पुष्य", ruler: "Saturn", deity: "Brihaspati", symbol: "Lotus/Udder", guna: "Tamas", motivation: "Dharma", degrees: "Cancer 3°20'–16°40'", shortDesc: "The nourisher. The most benefic of all nakshatras. Saturn here is disciplined nourishment — patient, careful, deeply sustaining.", body: "Pushya is universally regarded as the most auspicious nakshatra for beginnings. It is the flower that feeds, the udder that nourishes. Saturn as its ruler adds structure to the nourishment — it does not give indiscriminately but provides what is genuinely needed." },
  { num: 9, name: "Ashlesha", sanskrit: "आश्लेषा", ruler: "Mercury", deity: "Nagas", symbol: "Coiled Serpent", guna: "Sattva", motivation: "Dharma", degrees: "Cancer 16°40'–30°", shortDesc: "The clinging serpent. Kundalini energy, hypnotic persuasion, the intelligence of what is coiled and waiting to rise.", body: "The serpent deities (Nagas) govern the hidden knowledge that moves through underground channels. Ashlesha natives often have extraordinary intuitive intelligence — they sense what is concealed, understand what is not said, and can influence others through means that remain invisible." },
  { num: 10, name: "Magha", sanskrit: "मघा", ruler: "Ketu", deity: "Pitrs (Ancestors)", symbol: "Throne", guna: "Tamas", motivation: "Artha", degrees: "Leo 0–13°20'", shortDesc: "The great one. The throne of royal authority. Ketu here gives access to the concentrated power of the ancestral lineage.", body: "Magha connects the native directly to the Pitrs — the ancestral spirits whose accumulated karma and merit flows through the bloodline. This nakshatra produces natural authority — not earned but inherited from the depth of lineage. The shadow: pride without cultivation." },
  { num: 11, name: "Purva Phalguni", sanskrit: "पूर्व फाल्गुनी", ruler: "Venus", deity: "Bhaga", symbol: "Fig Tree/Hammock", guna: "Rajas", motivation: "Kama", degrees: "Leo 13°20'–26°40'", shortDesc: "The fig tree. The nakshatra of rest, creative delight, and the pleasure of conjugal union. Bhaga's gift of marital happiness.", body: "Bhaga is the deity of blessing and good fortune in marriage and partnership. Purva Phalguni is where Venus expresses most freely — not the strategic Venus of Libra but the simple, delighted, sensory Venus who enjoys existing." },
  { num: 12, name: "Uttara Phalguni", sanskrit: "उत्तर फाल्गुनी", ruler: "Sun", deity: "Aryaman", symbol: "Bed/Two Legs", guna: "Rajas", motivation: "Moksha", degrees: "Leo 26°40'–Virgo 10°", shortDesc: "The friend who keeps promises. Aryaman governs the sacred bonds of friendship and contract. Solar nobility expressed through loyalty.", body: "Where Purva Phalguni is delight, Uttara Phalguni is commitment. The pleasure of the hammock becomes the structure of the bed — permanence, reliability, the long-term bond. Aryaman is the deity who makes alliances last." },
  { num: 13, name: "Hasta", sanskrit: "हस्त", ruler: "Moon", deity: "Savitar", symbol: "Palm of Hand", guna: "Rajas", motivation: "Moksha", degrees: "Virgo 10–23°20'", shortDesc: "The skilled hand. Savitar's nakshatra of craftsmanship and healing through direct touch.", body: "Hasta natives work with their hands — literally or symbolically. The healing that occurs through touch, through craft, through the direct manipulation of material reality. Savitar is the deity of creative power expressed through skilled action." },
  { num: 14, name: "Chitra", sanskrit: "चित्र", ruler: "Mars", deity: "Vishwakarma", symbol: "Pearl/Bright Jewel", guna: "Tamas", motivation: "Kama", degrees: "Virgo 23°20'–Libra 6°40'", shortDesc: "The brilliant. The divine architect's nakshatra — extraordinary aesthetic intelligence and the capacity to manifest beauty into material form.", body: "Vishwakarma is the architect of the gods — the one who built their palaces, their weapons, their vehicles. Chitra produces the native with an almost painful awareness of beauty: they cannot leave ugliness undisturbed. They must make things beautiful." },
  { num: 15, name: "Swati", sanskrit: "स्वाति", ruler: "Rahu", deity: "Vayu", symbol: "Coral/Young Sprout", guna: "Tamas", motivation: "Artha", degrees: "Libra 6°40'–20°", shortDesc: "The independent one. The blade of grass that bends in Vayu's wind and survives precisely through its flexibility.", body: "Swati is the nakshatra of complete self-sufficiency. Vayu (wind) bends the grass; the grass does not break. This nakshatra produces traders, diplomats, and those who navigate through adaptability rather than force — moving with circumstances while maintaining an invisible rootedness." },
  { num: 16, name: "Vishakha", sanskrit: "विशाखा", ruler: "Jupiter", deity: "Indra-Agni", symbol: "Triumphal Arch/Potter's Wheel", guna: "Rajas", motivation: "Dharma", degrees: "Libra 20°–Scorpio 3°20'", shortDesc: "The forked. Two deities — Indra (worldly power) and Agni (spiritual fire) — held in tension. The nakshatra of those who pursue both dharma and artha simultaneously.", body: "Vishakha's symbol is the triumphal arch — you pass through it to reach victory. But the arch has two pillars: worldly achievement and spiritual aspiration. Vishakha natives are never satisfied with either alone; they must have both, and the tension between them is the source of their unusual intensity." },
  { num: 17, name: "Anuradha", sanskrit: "अनुराधा", ruler: "Saturn", deity: "Mitra", symbol: "Lotus/Triumphal Arch", guna: "Tamas", motivation: "Dharma", degrees: "Scorpio 3°20'–16°40'", shortDesc: "The friend. Mitra's nakshatra of sacred friendship and loyalty maintained through difficulty.", body: "Mitra is the deity of alliances, of the sacred contract between equals. Anuradha produces devotional friendship — the capacity to maintain bonds through difficulty, distance, and time. Saturn as ruler adds longevity and structure to Mitra's warmth: these friendships do not fade." },
  { num: 18, name: "Jyeshtha", sanskrit: "ज्येष्ठा", ruler: "Mercury", deity: "Indra", symbol: "Circular Talisman/Earring", guna: "Rajas", motivation: "Artha", degrees: "Scorpio 16°40'–30°", shortDesc: "The eldest. The chief. Indra's nakshatra of protective authority and the burden of leadership.", body: "Jyeshtha means 'the eldest' — those born here carry responsibility for others constitutionally. Indra is the king of the gods: his power is real, his burden is immense. Jyeshtha natives often feel the weight of leadership before they've formally claimed it." },
  { num: 19, name: "Mula", sanskrit: "मूल", ruler: "Ketu", deity: "Nirriti", symbol: "Bundle of Roots/Lion's Tail", guna: "Tamas", motivation: "Kama", degrees: "Sagittarius 0–13°20'", shortDesc: "The root. Nirriti — goddess of dissolution — pulls up what must be uprooted. The nakshatra of radical transformation through the elimination of what cannot serve.", body: "Mula is among the most feared nakshatras in popular Jyotish — and among the most misunderstood. Nirriti does not destroy for destruction's sake; she eliminates what blocks the root's access to deeper nourishment. Mula natives often experience radical upheaval that eventually reveals a deeper foundation." },
  { num: 20, name: "Purva Ashadha", sanskrit: "पूर्व आषाढ़ा", ruler: "Venus", deity: "Apas (Water Deity)", symbol: "Fan/Winnowing Basket", guna: "Rajas", motivation: "Moksha", degrees: "Sagittarius 13°20'–26°40'", shortDesc: "The invincible. Purification through water. The warrior who cannot be defeated because they have transcended the fear of loss.", body: "Apas is the deity of purifying water — the cosmic cleanser who prepares the warrior for invincibility not through armor but through purity. Purva Ashadha produces the native whose strength comes from what they have released rather than what they hold." },
  { num: 21, name: "Uttara Ashadha", sanskrit: "उत्तर आषाढ़ा", ruler: "Sun", deity: "Vishvadevas (Universal Gods)", symbol: "Elephant Tusk/Plank", guna: "Rajas", motivation: "Moksha", degrees: "Sagittarius 26°40'–Capricorn 10°", shortDesc: "The universal victory. Ten divine intelligences simultaneously governing permanent, unchallengeable achievement.", body: "Where Purva Ashadha is the preparatory purification, Uttara Ashadha is the final, permanent victory. The Vishvadevas are ten gods in one — collective divine intelligence aligned toward a single result. What Uttara Ashadha achieves cannot be taken away." },
  { num: 22, name: "Shravana", sanskrit: "श्रवण", ruler: "Moon", deity: "Vishnu", symbol: "Three Footprints/Ear", guna: "Rajas", motivation: "Artha", degrees: "Capricorn 10–23°20'", shortDesc: "The listener. Vishnu's nakshatra of cosmic attentiveness — the capacity to hear the order beneath surface noise.", body: "Shravana means 'to hear.' Vishnu maintains cosmic order through listening — through knowing what is happening in all three worlds simultaneously. Shravana natives have an extraordinary capacity for learning through listening, for connecting information across vast distances, for knowing what others do not share." },
  { num: 23, name: "Dhanishtha", sanskrit: "धनिष्ठा", ruler: "Mars", deity: "Ashta Vasus (Eight Gods of Abundance)", symbol: "Drum/Flute", guna: "Tamas", motivation: "Dharma", degrees: "Capricorn 23°20'–Aquarius 6°40'", shortDesc: "The wealthy. The eight Vasus govern material abundance through rhythmic discipline. The nakshatra of musical rhythm and extraordinary material success.", body: "The eight Vasus are the cosmic principles of material existence — earth, water, fire, air, sky, moon, sun, and stars. Dhanishtha is governed by all eight simultaneously: the fullness of material abundance expressed through rhythmic discipline. Mars as ruler adds the warrior's capacity to acquire and defend." },
  { num: 24, name: "Shatabhisha", sanskrit: "शतभिषज्", ruler: "Rahu", deity: "Varuna", symbol: "Empty Circle (100 Stars)", guna: "Tamas", motivation: "Dharma", degrees: "Aquarius 6°40'–20°", shortDesc: "The hundred healers. One hundred stars forming a circle with an empty center — the symbol of completion through solitude. Varuna's ocean of hidden cosmic law.", body: "Shatabhisha is the most mysterious of nakshatras. The empty circle at its center is not absence but potential — the zero from which all numbers arise. Varuna governs the hidden ocean of cosmic law (rita) — the invisible order that underlies visible reality. Those with planets here work with what cannot be seen or measured. The '100 physicians' are 100 healing forces operating from Patala itself — below the surface of ordinary consciousness." },
  { num: 25, name: "Purva Bhadrapada", sanskrit: "पूर्व भाद्रपद", ruler: "Jupiter", deity: "Aja Ekapada (One-Footed Serpent)", symbol: "Sword/Two Front Legs of Funeral Cot", guna: "Tamas", motivation: "Artha", degrees: "Aquarius 20°–Pisces 3°20'", shortDesc: "The one-footed serpent of the deep. Single-pointed intensity. The nakshatra of transformation through fire-walking.", body: "Aja Ekapada is a mysterious deity — a one-legged cosmic serpent dwelling in the atmosphere. Purva Bhadrapada produces the native of fierce single-pointed focus who walks through fire to reach what they are building. Jupiter here is the wise guide through the most extreme experiences." },
  { num: 26, name: "Uttara Bhadrapada", sanskrit: "उत्तर भाद्रपद", ruler: "Saturn", deity: "Ahir Budhnya (Serpent of the Deep)", symbol: "Twin Snakes/Two Rear Legs of Funeral Cot", guna: "Tamas", motivation: "Kama", degrees: "Pisces 3°20'–16°40'", shortDesc: "The serpent of the cosmic deep. The wisdom that lives at the very bottom of existence. Saturn here produces the most patient, unconditional love.", body: "Ahir Budhnya dwells in the deepest cosmic waters — the serpent who holds up the earth from below. Saturn as ruler of this Piscean nakshatra creates a paradox: the crystallizer in the dissolver. The result is profound patience and depth — the native who understands that what is deepest in the water is also what is most permanent." },
  { num: 27, name: "Revati", sanskrit: "रेवती", ruler: "Mercury", deity: "Pushan", symbol: "Fish (Pair)/Drum", guna: "Sattva", motivation: "Moksha", degrees: "Pisces 16°40'–30°", shortDesc: "The wealthy. Pushan — the nourishing shepherd — guides souls safely from one world to the next. Infinite compassion at the cycle's completion.", body: "Revati is the final nakshatra — the completion of the entire zodiacal journey. Pushan is the deity who lights the way through darkness, who guides the soul safely across the threshold between worlds. Mercury as ruler of this final Piscean nakshatra creates an unusual intelligence: one that communicates across worlds, across the boundary of death itself." },
];

export const yogas = [
  {
    slug: "raja-yoga",
    name: "Raja Yoga",
    sanskrit: "राज योग",
    category: "Power",
    rarity: "Common in partial forms, rare in full strength",
    shortDesc: "The yoga of kings. Kendra and trikona lords in combination — producing authority, recognition, and elevated status.",
    formation: "A lord of a kendra house (1, 4, 7, 10) forms a conjunction, mutual aspect, or sign exchange with a lord of a trikona house (1, 5, 9). The 1st house lord participates in the most powerful forms since it is simultaneously a kendra and trikona lord.",
    results: "Worldly authority and recognition. The strength of the yoga depends on the planets involved, their dignities, the houses they occupy, and the dasha period required for activation. A Raja Yoga does not automatically produce results — it requires the dasha of one of the participating planets or a powerful transit to trigger it.",
    depth: "The concept of Raja Yoga reveals something profound about the structure of power in the Vedic worldview: authority (kendra/action) must be rooted in dharma (trikona/purpose) to be legitimate and lasting. A kendra lord alone produces action without direction. A trikona lord alone produces aspiration without capacity. Their union produces directed power — the capacity to act in alignment with one's deepest purpose. This is why the most sustainable worldly success always has a dharmic quality to it: it is Raja Yoga expressing naturally.",
    secretKnowledge: "The most powerful Raja Yogas involve the 9th lord (highest dharma) connecting with the 10th lord (highest worldly action). This combination — dharma meeting karma — is the foundation of what ancient texts call Dharmakarmadhipati Yoga. When these two lords are in mutual kendra (particularly the 4th or 10th from each other), the yoga produces results that feel fated: as if the native could not have become anything other than what they became.",
  },
  {
    slug: "viparita-raja-yoga",
    name: "Viparita Raja Yoga",
    sanskrit: "विपरीत राज योग",
    category: "Reversal",
    rarity: "Uncommon, easily misidentified",
    shortDesc: "Rising through others' difficulties. The lords of the dusthana houses in mutual connection — producing power through crisis, collapse, and the transformation of suffering.",
    formation: "Lords of the 6th, 8th, and 12th houses (dusthanas) form mutual conjunctions, sign exchanges, or powerful aspects — without strong benefic interference. Three forms: Harsha (6th lord in 6th/8th/12th), Sarala (8th lord in 6th/8th/12th), Vimala (12th lord in 6th/8th/12th).",
    results: "The native rises while others around them fall. They gain through crises that defeat others. Their losses are eventually revealed as profound gains. The mechanism: when the lords of difficulty are themselves in difficulty, the difficult domains (disease, debt, hidden enemies) become self-canceling — they destroy each other rather than the native.",
    depth: "Viparita Raja Yoga is the most counterintuitive yoga in Jyotish — and the most instructive about the nature of karma. The dusthana lords, when strong in dusthanas, are experts in their own domain of difficulty. They become powerful navigators of exactly the terrain that defeats ordinary charts. This is why some of the most resilient, powerful individuals have charts filled with 'difficult' planetary combinations: the difficulty itself has become the source of extraordinary competence.",
    secretKnowledge: "The timing of Viparita Raja Yoga is crucial: its results typically manifest during the dasha of the yoga-forming planets, often preceded by a period of apparent crisis. The native may experience what looks like catastrophic loss — career collapse, health crisis, relationship failure — only to discover that the collapse cleared the space for something of far greater power. The yoga cannot be read in isolation from the dasha timeline. A Sarala Yoga (8th lord strong in dusthana) may require the 8th lord's dasha to manifest — and that dasha may come only in the second half of life.",
  },
  {
    slug: "dhana-yoga",
    name: "Dhana Yoga",
    sanskrit: "धन योग",
    category: "Wealth",
    rarity: "Multiple partial forms in most charts",
    shortDesc: "The yoga of material accumulation. Lords of the wealth houses in connection — producing financial resources through multiple streams.",
    formation: "Lords of the 2nd house (accumulated wealth), 11th house (income and gains), and/or the lagna lord connect through conjunction, mutual aspect, or sign exchange. The lagna lord's involvement is essential for the yoga to manifest personally.",
    results: "Material wealth, financial resources, multiple income streams. The quality of wealth depends on the planets involved: Jupiter-related Dhana Yoga produces wealth through knowledge and dharma; Venus-related produces wealth through beauty and relationship; Saturn-related produces wealth through sustained effort and structural enterprise.",
    depth: "The most overlooked Dhana Yoga formation involves the 5th and 9th lords (trikona lords) in connection with the 2nd and 11th lords. These produce wealth that flows from dharmic sources — teaching, creative work, philosophical output, spiritual service. Ancient texts distinguish between wealth that 'comes' (2nd/11th connections) and wealth that 'flows' (trikona-to-wealth-house connections). The former is accumulated; the latter is generative. The most sustainable forms of wealth in a chart combine both: accumulated capacity that becomes a source of ongoing generation.",
    secretKnowledge: "The most powerful Dhana Yoga is one where the 2nd and 11th lords are in their own signs or exaltation AND in a trikona house. This creates both the accumulative capacity and the dharmic legitimacy for wealth. What most practitioners miss: the Dhana Yoga must be activated by transit AND supported by a relevant dasha. A chart with extraordinary Dhana Yogas that remains in the dasha of a 6th or 12th lord planet throughout the prime wealth-building years may not manifest those yogas until Saturn Mahadasha — which may arrive precisely when the yogas are finally activated.",
  },
  {
    slug: "chandra-mangala-yoga",
    name: "Chandra Mangala Yoga",
    sanskrit: "चन्द्र मङ्गल योग",
    category: "Commerce",
    rarity: "Common",
    shortDesc: "The yoga of trade and entrepreneurial wealth. Moon and Mars in conjunction or mutual aspect — the emotional drive meeting the initiating force.",
    formation: "The Moon and Mars are conjunct in the same sign, or in mutual 7th aspect (180° apart). The conjunction form is more powerful; mutual aspect is still significant. The yoga operates even when one or both planets are in debilitation, though the expression changes.",
    results: "Wealth through trade, commerce, and enterprise. The native has an instinctive drive to generate wealth through activity — they cannot remain passive when opportunities arise. The emotional intelligence of the Moon combines with Mars's executive capacity to produce the prototype of the merchant-warrior: someone who can both sense opportunity and act on it without hesitation.",
    depth: "The Chandra Mangala Yoga is particularly interesting when it occurs in Cancer (Moon's own sign with Mars debilitated). Parashara mentions this specifically: even with Mars debilitated, the yoga produces wealth — but the mechanism shifts. Where ordinary Chandra Mangala produces wealth through direct trade and enterprise, the Cancer version produces wealth through emotional intelligence in commerce: the native reads markets, relationships, and opportunities through feeling rather than analysis, and this intuitive commercial sense can be extraordinarily precise.",
    secretKnowledge: "The yoga's output is modulated by the houses involved. Moon and Mars conjunct in the 2nd house: direct accumulation through trade. In the 10th: trade becomes a public career, visible enterprise, recognized commercial activity. In the 11th: gains from commerce arrive through networks, groups, and collective activity. In the 7th: business partnerships are the vehicle for commercial wealth. In the 8th: wealth through trading in what others fear or avoid — the unusual, the transformational, the financially complex.",
  },
  {
    slug: "lakshmi-yoga",
    name: "Lakshmi Yoga",
    sanskrit: "लक्ष्मी योग",
    category: "Divine Grace",
    rarity: "Rare in full form",
    shortDesc: "The yoga of the goddess of abundance. When fully formed, produces extraordinary wealth, beauty, and grace. When partial, produces partial blessings in the specific domain activated.",
    formation: "Venus in own sign (Taurus or Libra) or exaltation (Pisces), placed in a kendra (1,4,7,10) or trikona (1,5,9), with the 9th lord simultaneously strong. The lagna must also be strong for the yoga to manifest through the native rather than pass through them.",
    results: "In full form: extraordinary material abundance, physical beauty, harmonious relationships, artistic accomplishment, social grace, and a quality of effortless prosperity that others observe with wonder. In partial form: whichever component of the yoga is strongest manifests most clearly — a strong 9th lord alone produces dharmic prosperity; a strong Venus in own sign produces beauty and relationship gifts.",
    depth: "Lakshmi Yoga reveals the Vedic understanding of prosperity as multi-dimensional. The goddess Lakshmi is not merely wealth — she is the quality of grace, beauty, and effortless flow that wealth accompanies when it is dharmic. The yoga requires Venus (beauty, refinement), the 9th lord (dharma, grace, fortune), and a strong lagna (the capacity to embody rather than merely receive). Without lagna strength, the conditions for abundance may exist in the chart but the native cannot fully access or maintain them.",
    secretKnowledge: "The rarest form of Lakshmi Yoga involves Venus exalted in Pisces in the 9th house — the house of the highest dharma — with the 9th lord (Jupiter for Cancer lagna) strong in a kendra. This creates a 'double dharma' configuration: Venus in the sign of transcendence in the house of grace, with Jupiter (Venus's exaltation dispositor in Pisces) simultaneously strong. Charts with this configuration produce figures whose prosperity and beauty are inseparable from their spiritual function — teachers, artists, and wisdom-keepers whose material abundance is a direct expression of their dharmic output.",
  },
  {
    slug: "neecha-bhanga-raja-yoga",
    name: "Neecha Bhanga Raja Yoga",
    sanskrit: "नीच भङ्ग राज योग",
    category: "Cancellation & Reversal",
    rarity: "Moderate — cancellations are common; full Raja Yoga from them is rare",
    shortDesc: "The yoga of the fall and the recovery. A debilitated planet whose weakness is cancelled by specific conditions produces results paradoxically stronger than simple dignity.",
    formation: "A planet in debilitation has its neecha (fall) cancelled when: (1) the lord of the debilitation sign is in a kendra from lagna or Moon, OR (2) the planet that would exalt in that sign is in a kendra from lagna or Moon, OR (3) the debilitated planet is in mutual aspect with its own sign lord, OR (4) the debilitated planet exchanges signs with another planet. Multiple conditions multiply the yoga's strength.",
    results: "The planet that falls and is caught produces results more powerful than a planet that was always strong. The mechanism: the fall creates a crisis that forces the planet to develop its significations far beyond ordinary necessity. The recovery then expresses those amplified significations in the world. Mars debilitated in Cancer and cancelled: the warrior who learned to fight through emotion becomes more psychologically sophisticated than any Mars in Aries could be.",
    depth: "Neecha Bhanga reveals the Vedic understanding of grace through difficulty — the theological teaching that what falls and is lifted is stronger at the point of breaking than what was never tested. This is not consolation philosophy; it is precise astrological observation. The debilitated planet's significations are forced to develop through an unconventional path. Where an ordinary dignified planet expresses its significations through conventional means, the fallen-and-recovered planet must find alternative routes — and those alternative routes become the source of unusual depth and power.",
    secretKnowledge: "The most powerful Neecha Bhanga involves the simultaneous debilitation of two planets with mutual cancellation conditions. Mars debilitated in Cancer, Moon (Cancer's lord) simultaneously in a kendra — the falling planet's lord is in the position that cancels the fall. This double operation creates what some teachers call 'Mahaneecha Bhanga' — where both the debilitation and the cancellation are extremely prominent in the chart. The native experiences profound difficulty in the significations of both planets, followed by a recovery that makes those very significations the source of their most remarkable accomplishments.",
  },
];

export const lokas = [
  { name: "Satya Loka", sanskrit: "सत्य लोक", level: 7, color: "rgba(255,248,220,0.6)", symbol: "∞", planet: "—", house: "12th (highest)", description: "The plane of absolute truth. Pure undifferentiated consciousness — Brahma's realm. No karma reaches here because karma requires the subject-object split that dissolves at this frequency. The 12th house in its highest expression points here: not dissolution of the self but dissolution of the boundary between self and everything.", jyotishConnection: "Planets in the 12th house, when they operate at their highest frequency, are accessing Satya Loka consciousness — expressing their significations not through personal gain but through dissolution into something larger than the individual chart.", depth: "Satya Loka is not a destination reached by spiritual practice alone — it is the ground of all existence that was never absent. The Jyotishi who reads a chart is already in Satya Loka from one perspective; it is only from another perspective that the chart seems to matter." },
  { name: "Tapa Loka", sanskrit: "तप लोक", level: 6, color: "rgba(200,168,76,0.5)", symbol: "🜂", planet: "Saturn (highest)", house: "9th/12th", description: "The plane of purifying austerity. Where tapas — the heat generated by sustained spiritual discipline — burns away karmic impurity. Saturn at his highest operates here: not restriction but alchemical transformation. What enters Tapa Loka as karma exits as purified consciousness.", jyotishConnection: "Saturn afflictions in the natal chart that do not resolve through worldly remedies are often Tapa Loka processes: the difficulty is not circumstantial but alchemical. Recognizing this changes the native's relationship to the affliction entirely.", depth: "The crucial insight about Tapa Loka: suffering that does not change the quality of consciousness is not tapas. Tapas always transforms. If a Saturn affliction is merely suffered without producing inner transformation, the heat is being wasted. Tapas requires the conscious participation of the native in their own purification." },
  { name: "Jana Loka", sanskrit: "जन लोक", level: 5, color: "rgba(200,200,255,0.4)", symbol: "♃", planet: "Jupiter", house: "5th", description: "The plane of creative intelligence. Where dharmic creativity originates before descending into form. Jupiter's highest function operates here — not merely wisdom but the creative intelligence that generates wisdom. Purva punya (past-life merit) is stored and released from Jana Loka.", jyotishConnection: "A strong Jupiter in the 5th house, or the 5th lord well-placed with Jupiter, creates a channel between Jana Loka and the native's creative expression. The insight that 'comes from nowhere' during a Jupiter period is Jana Loka intelligence descending through the channel the yoga has created.", depth: "Jana Loka explains why genuine creative breakthroughs cannot be forced. They must be received from the plane where they originate. The practice of creating the conditions for creative intelligence to descend — through study, meditation, and dharmic living — is the Jana Loka practice that the 5th house and Jupiter govern." },
  { name: "Maha Loka", sanskrit: "मह लोक", level: 4, color: "rgba(100,180,255,0.4)", symbol: "✦", planet: "All Grahas collectively", house: "Zodiac itself", description: "The great plane. Where cosmic forces organize into the intelligible patterns that the Jyotishi glimpses when reading a chart. The 27 nakshatras in their highest sense are Maha Loka intelligences — specific organizing principles of the cosmic field expressing distinct qualities of consciousness.", jyotishConnection: "The act of chart reading is a Maha Loka perception — the Jyotishi momentarily accesses the plane where the patterns are organized. This is why genuine chart reading feels like recognition rather than calculation: the Jyotishi is perceiving a Maha Loka pattern, not constructing an interpretation.", depth: "Maha Loka is the plane where astrology actually operates. The birth chart is not a map of Bhuloka events — it is a Maha Loka pattern temporarily visible from Bhuloka through the precision of astronomical calculation. This is why Jyotish can be so extraordinarily precise: it is reading the actual organizing intelligence of the cosmic field, not merely correlating statistics." },
  { name: "Deva Loka", sanskrit: "देव लोक", level: 3, color: "rgba(232,192,96,0.5)", symbol: "☽", planet: "Jupiter, Sun, Venus", house: "9th, 5th", description: "The plane of divine intelligences. The devas are not mythological characters — they are specific intelligences governing specific domains of existence. The nava grahas are their executive agents: each planet is a deva's instrument of expression in the physical universe. To propitiate a planet is to communicate with its governing deva.", jyotishConnection: "Jupiter transiting the natal lagna is a Deva Loka event descending into Bhuloka — a moment when the specific intelligence of the dharma-principle directly touches the native's embodied self. This is why Jupiter-lagna transits feel qualitatively different from Jupiter transiting other houses: the grace is more direct, less mediated.", depth: "The deva-graha relationship explains why planetary remedies (mantras, gemstones, rituals) can have effects beyond what a purely physical model would predict. The remedy is not affecting the planet in the sky — it is communicating with the deva-intelligence that the planet represents, modulating the quality of that intelligence's expression in the native's life." },
  { name: "Bhuva Loka", sanskrit: "भुव लोक", level: 2, color: "rgba(100,200,150,0.4)", symbol: "☿", planet: "Mercury, Moon", house: "3rd, 12th (night-time)", description: "The intermediate plane — between visible and invisible. Where the mind operates, where dreams occur, where thought-forms gestate before becoming physical events. Mercury and the Moon are primarily Bhuva Loka planets: they mediate between the higher planes and Bhuloka, translating cosmic intelligence into mental experience.", jyotishConnection: "Mercury's retrograde periods are often experienced as Bhuva Loka events: the mediating function reverses, and mental constructs that were operating automatically are brought back into conscious awareness for revision. This is not malfunction but the necessary review of Bhuva Loka content before it crystallizes into Bhuloka events.", depth: "The Bhuva Loka insight with the greatest practical application: every Bhuloka event first exists as a Bhuva Loka pattern. The native with a strong Moon and Mercury can sometimes perceive these patterns before they crystallize — not through prediction but through the quality of attention that Bhuva Loka sensitivity makes available. This is the mechanism of genuine intuition." },
  { name: "Bhuloka", sanskrit: "भू लोक", level: 1, color: "rgba(180,120,60,0.5)", symbol: "🜃", planet: "All Grahas", house: "All Houses", description: "The manifest earth plane. Where karma crystallizes into physical events. The entire drama of the birth chart — its events, relationships, gains and losses — plays out here. But Bhuloka is not the origin of these events: it is the screen on which they appear after having been organized in the higher planes.", jyotishConnection: "The Jyotishi who only reads Bhuloka-level results (this career, this relationship, this financial event) is reading one screen of a multi-level projection. The deeper reading asks: what Maha Loka pattern is producing this Bhuloka event? What Tapa Loka process is the apparent difficulty serving? This vertical reading of the chart is what transforms Jyotish from prediction into wisdom.", depth: "Bhuloka's most important function in the Jyotish framework: it is the plane of verification. The higher planes produce patterns; Bhuloka reveals whether those patterns have been accurately perceived by the Jyotishi. This is why empirical chart testing — checking predictions against actual events — is not spiritually inferior but epistemically essential." },
  { name: "Patala Loka", sanskrit: "पाताल लोक", level: 0, color: "rgba(80,100,160,0.6)", symbol: "♄☽", planet: "Saturn, Ketu", house: "8th, 12th", description: "Below Bhuloka. The subterranean realm where the deepest karmic processes complete themselves below the threshold of conscious awareness. Not hell in any moral sense — rather, the place where what cannot yet surface continues its formation in the dark. Varuna's ocean. The hidden process that becomes the visible event.", jyotishConnection: "An 8th house heavy chart is not a 'difficult' chart — it is a Patala Loka chart: the primary drama of the life occurs below the surface, in transformation processes that are invisible until the moment of crystallization. Such natives often feel that 'nothing is happening' during their most profound developmental periods. Everything is happening, in Patala.", depth: "The Patala Loka teaching that changes chart reading most fundamentally: afflictions in the 8th house are not problems to be solved but processes to be allowed. The Jyotishi who understands Patala reads the 8th house not as difficulty but as depth — recognizing that what is forming in the subterranean plane is being prepared with extraordinary precision for the moment of surfacing." },
];

export const dashas = [
  { planet: "Ketu", years: 7, order: 1, color: "#b06840", essence: "The Dissolver", description: "Past-life themes surface. Sudden events strip away the inessential. Ketu does not build — he reveals what was always true beneath the constructed identity. Losses in Ketu dasha are rarely losses; they are uncoverings of what was never actually one's own.", innerDashas: ["Ketu-Ketu","Ketu-Venus","Ketu-Sun","Ketu-Moon","Ketu-Mars","Ketu-Rahu","Ketu-Jupiter","Ketu-Saturn","Ketu-Mercury"], depth: "Ketu dasha initiates the 120-year cycle with dissolution — a counter-intuitive beginning that makes perfect sense once understood. Before any authentic building can occur, the false structures accumulated in previous cycles must be dissolved. The native entering Ketu dasha is being prepared, not punished." },
  { planet: "Venus", years: 20, order: 2, color: "#e0a868", essence: "The Beautifier", description: "The longest dasha — 20 years of Venus's full range of expression. Relationships, creativity, luxury, artistic refinement, material accumulation. Venus dasha rewards those who have learned to receive rather than merely pursue. The quality of experience depends entirely on Venus's natal condition.", innerDashas: ["Venus-Venus","Venus-Sun","Venus-Moon","Venus-Mars","Venus-Rahu","Venus-Jupiter","Venus-Saturn","Venus-Mercury","Venus-Ketu"], depth: "The Venus-Venus antardasha that opens the Mahadasha is the period of maximum Venus purity — no other planetary influence modulates the expression. What Venus truly represents in the natal chart manifests with unusual directness during this opening sub-period. This is why the first year of Venus Mahadasha often feels like an arrival." },
  { planet: "Sun", years: 6, order: 3, color: "#f0c040", essence: "The Illuminator", description: "The briefest dasha — 6 years of concentrated solar energy. Authority, identity, and soul-purpose come into sharp focus. The self steps into its own light. What Surya rules in the natal chart receives its 6-year moment of maximum solar illumination.", innerDashas: ["Sun-Sun","Sun-Moon","Sun-Mars","Sun-Rahu","Sun-Jupiter","Sun-Saturn","Sun-Mercury","Sun-Ketu","Sun-Venus"], depth: "The shortness of Sun Dasha is not a limitation — it is intensity. Six years is sufficient for the soul's purpose to become unmistakably clear, for authority to be claimed or abdicated, for the father-principle to resolve in the psyche. What doesn't get done in 6 years with solar clarity needs to examine its relationship to the native's true soul-purpose." },
  { planet: "Moon", years: 10, order: 4, color: "#c8e0f8", essence: "The Mirror", description: "Emotional life becomes the primary terrain. The inner world creates the outer world with unusual directness during Moon Mahadasha. The Moon's natal nakshatra, sign, aspects, and phase at birth — all of it expresses fully. The mind is the protagonist.", innerDashas: ["Moon-Moon","Moon-Mars","Moon-Rahu","Moon-Jupiter","Moon-Saturn","Moon-Mercury","Moon-Ketu","Moon-Venus","Moon-Sun"], depth: "Moon Mahadasha's most important teaching: the native cannot escape their own psychology during this period. Circumstances become mirrors of inner states with unusual literalness. This makes Moon Dasha both the most psychologically productive dasha (for those willing to see themselves clearly) and the most psychologically challenging (for those who prefer to locate difficulty in external circumstances)." },
  { planet: "Mars", years: 7, order: 5, color: "#c84830", essence: "The Warrior", description: "Action, initiative, property, land, and courage are activated. Mars demands movement — passive waiting in Mars dasha creates stagnation and frustration. The years of Mars rarely allow neutrality. Choose or be chosen for.", innerDashas: ["Mars-Mars","Mars-Rahu","Mars-Jupiter","Mars-Saturn","Mars-Mercury","Mars-Ketu","Mars-Venus","Mars-Sun","Mars-Moon"], depth: "Mars Dasha is the testing ground for the native's relationship to desire and action. What one wants, and whether one is willing to fight for it, becomes the central question. The native who emerges from Mars Dasha knowing what they truly desire — and having taken concrete action toward it — is prepared for the expansions that follow." },
  { planet: "Rahu", years: 18, order: 6, color: "#9060b0", essence: "The Amplifier", description: "The second-longest dasha — 18 years of Rahu's insatiable amplification. Foreign elements, unconventional paths, worldly ambition at maximum intensity. Rahu grants what the soul craves at extreme intensity, teaching through the exhaustion of desire rather than its transcendence.", innerDashas: ["Rahu-Rahu","Rahu-Jupiter","Rahu-Saturn","Rahu-Mercury","Rahu-Ketu","Rahu-Venus","Rahu-Sun","Rahu-Moon","Rahu-Mars"], depth: "Rahu Dasha is where the soul's most intense worldly lessons are delivered. The native achieves — often extraordinarily — in the domain Rahu indicates. But the achievement itself becomes the teaching: what is gained at maximum Rahu intensity reveals, through possession, whether it was what the soul actually needed. Often it was not. This is the genius of the cosmic curriculum: you must have it fully before you can genuinely release it." },
  { planet: "Jupiter", years: 16, order: 7, color: "#e8c060", essence: "The Guru", description: "Wisdom, expansion, teaching, children, dharma — all activated and growing. Jupiter's dasha is the period of harvest. Whatever seeds of wisdom were planted across previous dashas now grow into their fullest expression.", innerDashas: ["Jupiter-Jupiter","Jupiter-Saturn","Jupiter-Mercury","Jupiter-Ketu","Jupiter-Venus","Jupiter-Sun","Jupiter-Moon","Jupiter-Mars","Jupiter-Rahu"], depth: "Jupiter Mahadasha is the period when the native becomes a source of wisdom rather than merely a seeker. The student becomes the teacher. The practitioner becomes the master. The capacity for grace — not merely receiving it but transmitting it — fully activates. This is why Jupiter Mahadasha is often experienced as the most expansive and benevolent period in an adult's life." },
  { planet: "Saturn", years: 19, order: 8, color: "#6880a8", essence: "The Crystallizer", description: "The great compression. Saturn's 19-year dasha is the period when karma accumulated across this and previous lifetimes crystallizes into permanent, inescapable form. What is built here lasts. What is avoided here becomes the next opening. Saturn rewards structural integrity above all.", innerDashas: ["Saturn-Saturn","Saturn-Mercury","Saturn-Ketu","Saturn-Venus","Saturn-Sun","Saturn-Moon","Saturn-Mars","Saturn-Rahu","Saturn-Jupiter"], depth: "Saturn Mahadasha is not a period of suffering — it is a period of construction. The suffering arises only where the native attempts to build on false foundations, where effort is applied in directions misaligned with Saturn's karmic mandate for the chart. The native who understands what Saturn requires and gives it — sustained effort, structural integrity, service, patience — finds Saturn Mahadasha to be the period of their most lasting and significant achievements." },
  { planet: "Mercury", years: 17, order: 9, color: "#60c880", essence: "The Discriminator", description: "Intellect, commerce, communication, skill refinement, and networking take center stage. Mercury's dasha is the period when the mind finds its most effective external expression. Ideas become enterprises. Knowledge becomes craft. Discrimination becomes wisdom.", innerDashas: ["Mercury-Mercury","Mercury-Ketu","Mercury-Venus","Mercury-Sun","Mercury-Moon","Mercury-Mars","Mercury-Rahu","Mercury-Jupiter","Mercury-Saturn"], depth: "Mercury Mahadasha is the period of articulation — when what was accumulated through experience across previous dashas finally finds its most precise verbal, written, and commercial expression. The teacher who has been teaching for decades discovers in Mercury Dasha that they can now write the book that systematizes everything they know. The trader who has been trading discovers the framework that makes their intuition teachable." },
];

export const encyclopediaTopics = [
  { slug: "ashtakavarga", title: "Ashtakavarga", category: "Technical", description: "The point-based transit analysis system. Each of the seven classical planets assigns benefic points to specific houses, revealing exactly which houses are strongest for each planet's transit — the most precise timing tool in Jyotish." },
  { slug: "divisional-charts", title: "Divisional Charts (Vargas)", category: "Technical", description: "The 16 sub-charts that reveal specific life domains with extraordinary precision. The D-9 Navamsa for marriage and dharma, D-10 Dashamsha for career, D-4 Chaturthamsha for property, and 13 others — each a complete lens into a specific dimension of existence." },
  { slug: "muhurta", title: "Muhurta — Electional Astrology", category: "Technical", description: "The art and science of choosing auspicious times for important actions. From marriage to business launch to surgery to travel — Muhurta reveals the cosmic windows when Bhuloka is most aligned with the higher planes." },
  { slug: "brihat-parashara", title: "Brihat Parashara Hora Shastra", category: "Classical Texts", description: "The foundational text of Jyotish — the comprehensive knowledge transmitted by the sage Parashara. The BPHS contains knowledge that contemporary practitioners have only partially decoded. A systematic exploration of its most overlooked teachings." },
  { slug: "remedies", title: "Upayas — Remedial Measures", category: "Practice", description: "The Vedic system of planetary remedies: gemstones, mantras, yantras, charitable acts, fasting, ritual worship. How remedies work at the level of Kala rather than Samaya — and why most contemporary remedy prescriptions miss the depth of the classical system." },
  { slug: "karma-theory", title: "The Architecture of Karma", category: "Philosophy", description: "A complete philosophical treatment of karma from the Jyotish perspective. Sanchita, Prarabdha, Agami — the three karmas and their relationship to the natal chart, the dashas, and the possibility of free will within fate." },
  { slug: "purusha-prakriti", title: "Purusha & Prakriti", category: "Philosophy", description: "The metaphysical foundation beneath Jyotish. The Samkhya framework of 24 tattvas (the manifest field) and the 25th (the witnessing consciousness) — and why understanding this distinction changes how one reads a chart entirely." },
  { slug: "kala-time", title: "Kala — The Nature of Cosmic Time", category: "Philosophy", description: "The distinction between Samaya (sequential time) and Kala (depth-time). Why Saturn operates in Kala while other planets operate in Samaya. The Maha Yuga cycles, the nature of Kali Yuga, and the compressed evolutionary opportunity it offers." },
  { slug: "consciousness", title: "What the Chart Cannot See", category: "Philosophy", description: "The meta-teaching of Jyotish: the chart maps Prakriti with extraordinary precision but cannot see the Purusha that is watching the chart. The highest function of Jyotish is dis-identification — using the map to transcend the need for the map." },
  { slug: "houses-deep", title: "The 12 Bhavas — Deep Reading", category: "Technical", description: "A house-by-house exploration that goes beyond standard keyword associations into the metaphysical function of each Bhava. The 8th house as Patala. The 12th as access to Satya Loka. The 5th as Jana Loka intelligence. Each house as a plane of consciousness." },
];

export const siteConfig = {
  name: "Kala Darshan",
  tagline: "काल दर्शन · Vision of Cosmic Time",
  description: "A complete encyclopedia of Jyotish and Vedic cosmology. Grahas, Nakshatras, Yogas, Dashas, Lokas, Karma, Kala, Purusha — the deepest knowledge of the Vedic astrological tradition, presented for the serious student.",
  email: "hello@kaladarshan.com",
  instagram: "@kaladarshan",
};
