"use client";
import { RevealSection, GoldDivider, ProseKala } from "@/components/ui";
import Link from "next/link";

const deepContent: Record<string, { sections: { heading: string; body: string }[] }> = {
  "ashtakavarga": { sections: [
    { heading: "What is Ashtakavarga", body: "Ashtakavarga is a system of point-based planetary strength assessment developed by Parashara. Each of the seven classical planets plus the Lagna assigns benefic points to specific houses based on their natal position. The total points in each house reveal exactly which areas of life receive maximum cosmic support — and which require sustained effort to activate." },
    { heading: "Bhinna Ashtakavarga — Individual Planet Charts", body: "Each planet generates its own Ashtakavarga. A planet transiting a house where its own Bhinna Ashtakavarga shows 4+ points delivers results. With fewer than 4 points, even the most auspicious transit struggles. This single insight explains why identical transits produce different results in different charts — they are not identical at the Ashtakavarga level." },
    { heading: "Sarva Ashtakavarga — The Master Map", body: "The Sarva Ashtakavarga is the sum of all eight individual charts. Houses with 28+ points are strong. Houses with fewer than 25 are weak. This creates a topographic map of your entire chart's receptivity to planetary influence — revealing the strong zones where life flows and the weak zones where effort produces disproportionately little return." },
    { heading: "Transit Prediction", body: "Before predicting any transit result, calculate the transiting planet's Bhinna Ashtakavarga score for the house it is entering. Saturn transiting the 7th with only 2 points of his own Ashtakavarga there: significant obstruction. Saturn transiting the 7th with 5 points: the transit may actually produce positive results despite Saturn's general malefic nature. This reverses many standard predictions and makes Ashtakavarga the most empirically reliable timing tool in Jyotish." },
    { heading: "What Most Practitioners Miss", body: "The Ashtakavarga is simultaneously a natal analysis tool and a predictive tool. The house with the highest Sarva score is not just where transits work best — it is where the native's karma is most aligned with cosmic support. The house with the lowest score is not simply where transits struggle — it is where the native's karma is working against the cosmic grain, requiring either sustained effort or graceful acceptance." }
  ]},
  "divisional-charts": { sections: [
    { heading: "The Principle of the Vargas", body: "The Varga charts are one of Jyotish's most powerful and most underutilized tools. Each Varga divides the 30° zodiac sign into precise subdivisions, creating a secondary chart revealing specific life domains with extraordinary precision. Where the Rashi chart shows the overall karmic architecture, the Vargas show the fine structure of each specific domain." },
    { heading: "D-9 Navamsa — The Soul Chart", body: "The Navamsa (ninth division) is the most important divisional chart after the Rashi. It reveals the dharmic quality of the soul, the nature of the spouse and marriage, and the destiny unfolding in the second half of life. A planet in its own sign, exaltation, or friendly sign in the Navamsa gains Vargottama strength — extraordinary power that modifies the natal chart significantly." },
    { heading: "D-10 Dashamsha — Career", body: "The Dashamsha reveals career, public reputation, and professional dharma with precision far beyond the 10th house alone. The Dashamsha lagna shows the native's professional identity. The 10th house of the Dashamsha shows peak professional achievement. Strong planets in the Dashamsha's angular houses indicate domains where professional karma is most supported." },
    { heading: "D-4 Chaturthamsha — Property", body: "The Chaturthamsha reveals the karma around property, real estate, vehicles, and fundamental happiness. The condition of the 4th lord in the Chaturthamsha — its sign, house, and aspects — reveals the property karma with precision far beyond what the Rashi 4th house alone can show." },
    { heading: "D-60 Shashtiamsha — Pure Karma", body: "The most refined of all Vargas — dividing each sign into 60 parts of 0°30' each. It shows the pure karma of the soul, independent of the circumstances of the current incarnation. Its interpretation requires the most precise birth time (accurate to within minutes) and the deepest philosophical understanding. What is shown in the Shashtiamsha is karmic in the most fundamental sense." }
  ]},
  "muhurta": { sections: [
    { heading: "The Science of Auspicious Time", body: "Muhurta is the Jyotish science of electional astrology — selecting the most auspicious moment for important actions. Every beginning has a chart, and the quality of that chart determines the quality of the thing begun. The principle: choose the best available birth chart for the things you are creating." },
    { heading: "The Five Limbs — Panchanga", body: "Muhurta analysis centers on the Panchanga: Vara (weekday ruled by a planet), Tithi (lunar day — 30 cycle), Nakshatra (Moon's current station), Yoga (27 Sun-Moon combinations), and Karana (half-tithi, 11 types). A Muhurta is strongest when multiple Panchanga factors align auspiciously simultaneously." },
    { heading: "What to Avoid", body: "As important as selecting auspicious times is avoiding the inauspicious ones. Rahu Kala falls on every day at predictable times — approximately 90 minutes of Rahu's shadow-creating influence. Gulika Kala adds Saturn's constricting quality. Most traditional families automatically exclude these periods from any new beginning." },
    { heading: "Marriage Muhurta", body: "Marriage Muhurta is the most important and complex calculation because marriage creates karma unfolding over a lifetime. Critical: Venus and Jupiter must not be combust (within 10° of the Sun) on a wedding day. The Muhurta lagna's 7th house must be free of malefics. The Moon should not occupy the 8th from the Muhurta lagna." },
    { heading: "The Metaphysical Principle", body: "Why does Muhurta work? Because every beginning is a birth, and the birth chart of any beginning carries the same karmic weight as a human birth chart. The cosmos does not distinguish between the birth of a corporation, a marriage, or a child. Muhurta selects the best available birth chart for what you are creating — working within the native's karma to find the most dharmically aligned window." }
  ]},
  "karma-theory": { sections: [
    { heading: "Karma Beyond the Ledger", body: "Karma is not a cosmic ledger of sins. It is the precise, impersonal record of every pattern of consciousness active across incarnations — accumulating into the crystalline structure of present reality. These patterns do not wait passively — they actively organize the field of experience, creating tendencies, attracting circumstances, and generating the prarabdha that shapes the current life." },
    { heading: "Sanchita — The Storehouse", body: "The totality of accumulated karma from all past lives. Infinite in scope — most will never be experienced in a single lifetime. The 8th house and its lord in the natal chart are the visible index of Sanchita — showing where the hidden depths of accumulated karma are most active in this incarnation." },
    { heading: "Prarabdha — The Active Karma", body: "The karma selected for this lifetime — already crystallized, already inescapable, already in motion at birth. The birth chart is its precise map. You did not choose it in this life. But the consciousness that chose this incarnation chose the karma that required this precise chart. The lagna is how prarabdha is experienced from the inside." },
    { heading: "Agami — The Living Karma", body: "The karma being created right now. This is where free will lives: not in escaping prarabdha, but in the quality of consciousness with which prarabdha is met. The quality of response to fate becomes the seed of the next prarabdha. Same prarabdha, completely different agami — and therefore different future prarabdha." },
    { heading: "The Crystallization Model", body: "Karma accumulates as sediment over lifetimes. Under Kala-pressure (Saturn's function), it compresses from sediment to stone to crystal — becoming prarabdha: specific, structured, with a precise geometry. The dasha-transit nexus provides the final trigger: the snap from compressed mineral to crystallized event in Bhuloka." }
  ]},
  "purusha-prakriti": { sections: [
    { heading: "The Foundation Beneath Jyotish", body: "Before there are planets or houses or dashas, there is the fundamental metaphysical question the Vedic tradition answers more precisely than any other: what is the relationship between witnessing consciousness and the field it witnesses? The answer — Purusha and Prakriti — is the foundation beneath all of Jyotish." },
    { heading: "Purusha — The Witness", body: "The 25th tattva in Samkhya — beyond all others, prior to all manifest reality. Pure unmodified witnessing consciousness. It does not act, does not have karma, does not experience suffering in the ordinary sense. It simply witnesses. Every individual has a Purusha — the deep witnessing presence unchanged through every dasha, every transit, every life event." },
    { heading: "Prakriti — The Field", body: "The 24 tattvas — the entirety of manifest existence from Mahat (cosmic intelligence) to Prithvi (earth element). Everything the chart maps is Prakriti: the planets, the karma, the dashas, the life events. Prakriti is not inferior to Purusha — it is the field in which Purusha's witnessing occurs." },
    { heading: "The Fundamental Confusion", body: "The root of all suffering in the Samkhya framework is Avidya — the confusion of Purusha with Prakriti. The witnessing consciousness mistakes itself for the field being witnessed. The 'I' (Ahamkara — the ego, part of Prakriti) claims to be the Purusha. Jyotish at its deepest level is a technology of distinguishing the two." },
    { heading: "Practical Application", body: "Every planetary configuration maps a quality of Prakriti — a pattern of karma, a tendency in the field. The Jyotishi reads these patterns with maximum precision. But the deeper task is occasionally reminding the native: you are not the chart. The Cancer lagna, the Saturn in the 8th — these are configurations of Prakriti that the Purusha is witnessing. They are maps. They are not the traveler." }
  ]},
  "kala-time": { sections: [
    { heading: "Two Kinds of Time", body: "Samaya is sequential, measurable time — one moment following another. This is Mercury and Sun's time: instrumental, communicable, shared. Kala is something altogether different: not a sequence but a depth — the accumulation of pressure that makes things inevitable before they become visible. Kala does not tick forward; it deepens downward." },
    { heading: "Saturn as Kala Purusha", body: "Saturn moves at approximately 1 degree per 12 days, completing its orbit in 29.5 years — the slowest of all classical planets. The further a planet is from the radiant center, the more deeply it operates in Kala rather than Samaya. Saturn, furthest of the classical seven, is Kala's embodiment — slow, inevitable, geological." },
    { heading: "The Four Yugas", body: "The Maha Yuga cycle is Kala at its vastest scale — 4,320,000 years. Satya Yuga (1,728,000 years): full consciousness, direct human-divine connection. Treta Yuga (1,296,000): ritual becomes necessary. Dvapara Yuga (864,000): half-conscious, dharma and adharma in balance. Kali Yuga (432,000): maximum material density. We are approximately 5,125 years into Kali Yuga." },
    { heading: "Kali Yuga — The Accelerated Path", body: "Kali Yuga is simultaneously the most challenging and most opportunity-rich age. The veil between Purusha and Prakriti is at maximum thickness — making it harder to pierce but making any genuine piercing more powerful. In Satya Yuga, liberation comes relatively naturally. In Kali Yuga, any genuine spiritual accomplishment occurs against maximum friction — and that friction, properly directed, produces extraordinary tapas." },
    { heading: "How to Work with Kala", body: "You cannot use Samaya tools to solve a Kala problem. Effort, strategy, and activity are insufficient alone. Kala responds to depth, not speed. What works: structural integrity (building what is genuinely solid), patient sustained effort over long periods, and willingness to allow crystallization on its own timeline. Stop asking 'when will this end?' Start asking 'what is this completing?'" }
  ]},
  "consciousness": { sections: [
    { heading: "The Limit of the Map", body: "Jyotish is the most precise map of Prakriti ever developed. The nava grahas, 27 nakshatras, 12 bhavas, dashas, yogas, Ashtakavarga, 16 divisional charts — together a cartographic achievement of extraordinary precision. And yet: no map includes the cartographer. The birth chart cannot include the consciousness doing the observing. This is not a failure — it is Jyotish's highest teaching." },
    { heading: "Three Levels of Reading", body: "Level one: predictive — what events will occur and when. Entirely legitimate; Jyotish can predict with remarkable precision. Level two: psychological — what patterns of consciousness generate these events? Level three: liberational — what is the Purusha-Prakriti distinction this specific chart is designed to make vivid? The Rishis designed Jyotish for level three, not level one." },
    { heading: "Ajappa — The Breath That Remembers", body: "The Sikh tradition contributes what formal Jyotish does not provide: the practice. Waheguru synchronized with the natural breath cycle — Ajappa Jaap, the mantra that repeats itself without conscious initiation. This is what makes Jyotish sustainable. The chart tells you what Saturn is doing in the 8th house. Ajappa reminds you, breath by breath, what you are while Saturn does it." },
    { heading: "The Silence at the Center", body: "Shatabhisha's symbol is an empty circle — one hundred stars forming a ring around a void. This is the most precise symbol in all of Jyotish for what consciousness ultimately is: not the stars (the experiences, the karma, the chart) but the empty center around which they organize. Every chart has this silence at its center. The Jyotishi who can glimpse it is practicing at the highest frequency." },
    { heading: "When the Chart Completes Itself", body: "Every dasha exhausts itself. Every transit passes. Every yoga activates or its window closes. Eventually all prarabdha karma is experienced and released. What remains when the chart has fully completed its work is what was always there: the Purusha that was never actually bound by any of it. Jyotish accelerates this completion by making the karma's structure explicitly visible — so it can be met with full consciousness rather than unconscious reaction." }
  ]},
  "brihat-parashara": { sections: [
    { heading: "The Foundation Text", body: "The Brihat Parashara Hora Shastra is the foundational text of Jyotish — attributed to the sage Parashara, father of Vyasa. Presented as a dialogue between Parashara and his disciple Maitreya, it covers every dimension of Jyotish: grahas, rashi, bhavas, dashas, yogas, Ashtakavarga, divisional charts, muhurta, and remedies. Modern scholarship dates the current text to approximately the 7th-10th century CE." },
    { heading: "What Contemporary Practice Has Lost", body: "The BPHS contains approximately 100 chapters and 3,000+ shlokas. Contemporary Jyotish practice engages with perhaps 30% of this content. Most neglected: the Sudarshana Chakra chapters (reading simultaneously from lagna, Moon, and Sun); the Kalachakra Dasha system; detailed Ashtakavarga refinements including Trikona Shodhana; and the chapters on the relationship between birth chart and past-life karma patterns." },
    { heading: "The Planetary Avatars", body: "One of the most profound and least-discussed teachings: each graha is an avatar of Vishnu into a specific cosmic function. The Sun is Rama — the ideal king embodying perfect dharma. The Moon is Krishna — the beloved embodying perfect relationship. Mars is Narasimha — the fierce protector. Mercury is the Buddha — discrimination and enlightenment. Jupiter is Vamana — expansion and cosmic grace. Venus is Parashurama — the tantric warrior-sage. Saturn is Kurma — the tortoise, slow and foundational." },
    { heading: "How to Study the BPHS", body: "The BPHS is not a textbook to be read linearly — it is a reference text studied in layers. Study with a living teacher who provides the interpretive tradition (sampradaya). Read one section at a time until its meaning becomes clear both intellectually and experientially. Apply every technique to actual charts before moving to the next. Keep K.N. Rao's commentaries and Sanjay Rath's writings alongside — they represent two of the strongest living interpretive traditions." }
  ]},
  "remedies": { sections: [
    { heading: "What Remedies Actually Do", body: "Remedies do not change the natal chart. They do not cancel karma. They do not prevent the crystallization Kala has set in motion. What remedies do: they change the quality of the native's relationship to the planetary energy — their resonance with it, their capacity to work with it rather than against it, and sometimes the specific expression it takes within the range of possibilities the karma allows." },
    { heading: "Gemstones — Resonance Technology", body: "Each classical gemstone amplifies a specific planet's energy through resonant transmission. Critical rule: gemstones should only be worn for naturally benefic planets (Jupiter, Venus, Mercury, and sometimes Moon or Sun depending on the ascendant), or for the chart's ruling planets. Wearing a gemstone for a malefic — particularly Saturn or Rahu — amplifies malefic quality along with benefits, which is often counterproductive." },
    { heading: "Mantras — Sonic Technology", body: "Each planet has a Beeja (seed) mantra — a short, intense sound-formula creating a specific resonance in the subtle body. Extended repetition (traditionally 108 times daily, or 18,000-125,000 repetitions over a dedicated period) creates sustained resonance with the planetary intelligence. The most powerful practice is done at the planet's Hora, on the planet's day, during auspicious Ashtakavarga positions." },
    { heading: "Dana — Charitable Acts", body: "Dana (charitable giving) is among the most traditionally recommended remedies. By voluntarily giving away the significations of the afflicting planet, the native creates agami karma that counteracts the afflicting karma. For Saturn afflictions: giving to the poor, serving the elderly, donating oil lamps on Saturday evenings. The act works not transactionally but by reorienting consciousness toward the planet's highest expression." },
    { heading: "Yantras — Geometric Technology", body: "A Yantra is a geometric diagram encoding a specific planetary intelligence in visual form. Activated through specific mantra repetition and ritual installation, yantras function as stable focal points for planetary resonance in the native's living space. Where gemstones work through the physical body and mantras through the subtle body, yantras work through the spatial-environmental dimension — creating a field of planetary resonance in the space where the native spends significant time." }
  ]},
  "houses-deep": { sections: [
    { heading: "Beyond Keywords", body: "Standard Jyotish teaches house significations as keyword lists. The complete understanding includes the metaphysical function of each bhava — the specific type of consciousness-experience it generates, its corresponding loka, its relationship to the karmic architecture of the life, and what becomes possible when the house is fully activated versus suppressed." },
    { heading: "The 1st House — The Lagna", body: "Simultaneously the most personal and most cosmic point in the chart. Where the individual meets the universal — the precise zodiac degree rising at the birth moment, chosen by the soul to provide the exact Prakriti-vehicle required for the current prarabdha. The lagna lord is the most important planet in the entire chart. A strong lagna lord means genuine capacity to activate whatever the chart contains." },
    { heading: "The 5th House — Jana Loka's Window", body: "The window through which Jana Loka intelligence descends into the individual life. Purva Punya — past-life merit — is stored here and releases as what appear to be unearned blessings and natural talents. The native with a strong 5th seems to receive things others must work far harder to obtain. This is not injustice — it is the legitimate fruit of previous lifetimes' dharmic effort, now available as grace." },
    { heading: "The 8th House — Patala's Domain", body: "The most feared and most misunderstood house. It is Patala's window — where subterranean karma is most directly accessible. Its negative significations (death, sudden events, hidden enemies) and its positive ones (tantra, occult knowledge, transformational capacity, research) are both expressions of Patala: the extraordinary depth that becomes accessible when one descends below the surface. The native with a strong 8th is not cursed — they are a Patala-capable consciousness." },
    { heading: "The 12th House — The Portal", body: "The portal between Bhuloka and the higher lokas. Its significations — loss, foreign lands, isolation, spiritual practice — all point to the same principle: dissolution of the boundary between individual and universal. What is 'lost' in the 12th is not gone — it is dissolved into something larger. The native with a strong 12th is a Satya-Loka-aspiring consciousness: someone whose gravitational pull is toward the plane where individual boundaries dissolve into universal consciousness." }
  ]},
};

export default function EncyclopediaClient({ topic, prev, next, slug }: { topic: any; prev: any; next: any; slug: string }) {
  const content = deepContent[slug];
  return (
    <>
      <section style={{ minHeight: "55vh", display: "flex", flexDirection: "column", alignItems: "center", justifyContent: "center", textAlign: "center", padding: "140px 24px 80px", background: "linear-gradient(to bottom,#010208,#030810)" }}>
        <span style={{ fontFamily: "'Cinzel',serif", fontSize: ".65rem", letterSpacing: ".45em", color: "#6a5820", marginBottom: "16px", display: "block" }}>{topic.category.toUpperCase()} · ENCYCLOPEDIA</span>
        <h1 style={{ fontFamily: "'Cinzel Decorative',serif", fontSize: "clamp(1.8rem,5vw,3.8rem)", fontWeight: 700, color: "#f0d878", textShadow: "0 0 60px rgba(200,168,76,.2)", letterSpacing: ".04em", marginBottom: "28px", maxWidth: "800px" }}>{topic.title.toUpperCase()}</h1>
        <p style={{ maxWidth: "640px", fontSize: "1.15rem", fontStyle: "italic", color: "rgba(240,244,248,0.92)", lineHeight: 1.9 }}>{topic.description}</p>
      </section>
      <GoldDivider />
      <section style={{ background: "linear-gradient(to bottom,#030810,#050d1a)", padding: "80px 0 120px" }}>
        <div style={{ maxWidth: "900px", margin: "0 auto", padding: "0 48px" }}>
          <RevealSection>
            <ProseKala>
              {content?.sections.map((s, i) => (
                <div key={i}><h3>{s.heading}</h3><p>{s.body}</p></div>
              ))}
            </ProseKala>
          </RevealSection>
          <div style={{ marginTop: "60px", display: "flex", justifyContent: "space-between", borderTop: "1px solid rgba(255,255,255,.04)", paddingTop: "32px" }}>
            {prev ? <Link href={`/encyclopedia/${prev.slug}`} style={{ fontFamily: "'Cinzel',serif", fontSize: ".65rem", letterSpacing: ".18em", color: "#6a5820", textDecoration: "none" }}>← {prev.title}</Link> : <span />}
            {next ? <Link href={`/encyclopedia/${next.slug}`} style={{ fontFamily: "'Cinzel',serif", fontSize: ".65rem", letterSpacing: ".18em", color: "#6a5820", textDecoration: "none" }}>{next.title} →</Link> : <span />}
          </div>
        </div>
      </section>
    </>
  );
}
