import { notFound } from "next/navigation";
import { encyclopediaTopics } from "@/lib/data";
import { RevealSection, GoldDivider, ProseKala } from "@/components/ui";
import Link from "next/link";

export async function generateStaticParams() {
  return encyclopediaTopics.map(t => ({ slug: t.slug }));
}
export async function generateMetadata({ params }: { params: { slug: string } }) {
  const t = encyclopediaTopics.find(t => t.slug === params.slug);
  return { title: `${t?.title} | Kala Darshan Encyclopedia` };
}

const deepContent: Record<string, { sections: { heading: string; body: string }[] }> = {
  "ashtakavarga": {
    sections: [
      { heading: "What is Ashtakavarga", body: "Ashtakavarga (Sanskrit: eight divisions of strength) is a system of point-based planetary strength assessment developed by Parashara and elaborated in the Brihat Parashara Hora Shastra. Where most Jyotish analysis focuses on the natal position of planets in signs and houses, Ashtakavarga focuses on the transit performance of planets through the natal chart — revealing with mathematical precision exactly which houses are energized and which are depleted for each planet's movement through them." },
      { heading: "Bhinna Ashtakavarga — Individual Planet Charts", body: "Each of the seven classical planets (Sun, Moon, Mars, Mercury, Jupiter, Venus, Saturn) plus the Lagna generates its own Ashtakavarga chart. This is the Bhinna (individual) Ashtakavarga. In each planet's individual chart, every house receives a number of benefic points (0–8) based on Parashara's rules for that specific planet. A planet transiting a house where its own Bhinna Ashtakavarga shows 4+ points produces results. With fewer than 4 points, even the most auspicious transit struggles to deliver. This single insight explains why 'identical' transits produce different results in different charts — they are not identical at the Ashtakavarga level." },
      { heading: "Sarva Ashtakavarga — The Master Map", body: "The Sarva (total) Ashtakavarga is the sum of all eight individual Ashtakavarga charts. Each house receives a total score ranging from 0 to 56 points (7 planets + lagna × 8 maximum points each). Houses with 28+ points are strong — transiting planets deliver results here easily. Houses with fewer than 25 points are weak — even benefic transits struggle. The Sarva Ashtakavarga creates a topographic map of your entire chart's receptivity to planetary influence — revealing the strong zones where life flows with relative ease and the weak zones where effort produces disproportionately little return." },
      { heading: "Trikona Shodhana — Purification of Triangles", body: "One of the most powerful applications of Ashtakavarga is Trikona Shodhana — the reduction of points in the three trikona groups (houses 1-5-9, 2-6-10, 3-7-11, 4-8-12). By canceling the minimum value across each trikona group and then calculating the net strength, Trikona Shodhana isolates the genuine productive strength of each house from the raw score. This refinement makes Ashtakavarga analysis significantly more precise for timing predictions." },
      { heading: "Pinda — The Total Life Force", body: "The Pinda is the sum of all Sarva Ashtakavarga points in a chart — theoretically possible from 0 to 337. A Pinda above 337 (impossible in practice but theoretical maximum) would indicate maximum cosmic support. Practically, charts above 280 indicate strong overall support from cosmic forces; charts below 220 indicate significant challenges across multiple domains. The Pinda is the single-number summary of a chart's overall relationship with cosmic energy — though its meaning only becomes significant in context with the specific distribution of points across houses." },
      { heading: "Transit Prediction Using Ashtakavarga", body: "The most practical application: before making any prediction about a planetary transit, calculate the transiting planet's Bhinna Ashtakavarga score for the house it is entering. Saturn transiting the 7th house with only 2 points of its own Ashtakavarga in that house: the transit's obstructive potential is significant. Saturn transiting the 7th with 5 points: the transit may actually produce positive results despite Saturn's general malefic nature. This reverses many standard transit predictions and makes Ashtakavarga the most empirically reliable timing tool in the entire Jyotish system." },
      { heading: "What Most Practitioners Miss", body: "The Ashtakavarga is calculated from the natal chart — but the points in each house are not fixed qualities of that house. They are the natal chart's receptivity to each planet's transit through that house. This means the Ashtakavarga is simultaneously a natal analysis tool and a predictive tool. The house with the highest Sarva score is where life's blessings flow most naturally — not just where transits work best, but where the native's karma is most aligned with cosmic support. The house with the lowest score is not simply where transits struggle — it is where the native's karma is working against the cosmic grain." }
    ]
  },
  "divisional-charts": {
    sections: [
      { heading: "The Principle of the Vargas", body: "The Varga (divisional) charts are one of Jyotish's most powerful and most underutilized tools. Each Varga chart divides the 30° zodiac sign into precise subdivisions, creating a secondary chart that reveals specific life domains with extraordinary precision. Where the Rashi (natal) chart shows the overall karmic architecture of the life, the Vargas show the fine structure of each specific domain — how the karma expresses in that particular arena." },
      { heading: "D-1 Rashi — The Foundation", body: "The D-1 Rashi chart is the natal chart — the primary foundation from which all other charts are derived. Its strength or weakness directly affects all divisional charts. A planet that is strong in the D-1 and a specific Varga has double-strength in that Varga's domain. A planet that is weak in the D-1 and a Varga has double-weakness. The Rashi chart is never transcended by the Vargas — it is the root system from which all Varga branches grow." },
      { heading: "D-9 Navamsa — The Soul Chart", body: "The Navamsa (ninth division) is the single most important divisional chart after the Rashi. It divides each sign into 9 equal parts of 3°20', creating a complete secondary chart. The Navamsa reveals: (1) the dharmic quality of the soul — the deeper nature of the self beneath the Rashi personality, (2) the nature of the spouse and marriage relationship, (3) the 'destiny' that unfolds in the second half of life (after approximately age 36), and (4) the strength of planets — a planet in its own sign, exaltation, or a friendly sign in the Navamsa is 'Vargottama' and gains extraordinary power. Planets in Pushkara Navamsa (specific degrees) are especially blessed." },
      { heading: "D-10 Dashamsha — Career and Public Life", body: "The Dashamsha divides each sign into 10 equal parts of 3°, creating a chart specifically revealing career, public reputation, and professional dharma. What the 10th house in the Rashi shows broadly, the Dashamsha reveals with precision. The lagna and lagna lord of the Dashamsha show the native's professional identity and approach. The 10th house of the Dashamsha shows the peak professional achievement. Strong planets in the Dashamsha — particularly its lagna, 10th, and 11th houses — indicate domains where professional karma is most supported." },
      { heading: "D-4 Chaturthamsha — Property and Happiness", body: "The Chaturthamsha (fourth division) reveals the karma around property, real estate, vehicles, and fundamental happiness (sukha). The condition of the 4th lord in the Chaturthamsha — its sign, house, and aspects — reveals the property karma with precision far beyond what the Rashi 4th house alone can show. Strong 4th and 11th lords in the Chaturthamsha indicate strong property accumulation karma. Afflictions in the Chaturthamsha explain why a native with an apparently strong Rashi 4th house still struggles with property or happiness." },
      { heading: "D-12 Dwadashamsha — Parents and Ancestry", body: "The Dwadashamsha reveals the karma connected to parents, lineage, and ancestral inheritance — both material and karmic. The condition of the Sun in the Dwadashamsha reveals the father-karma. The Moon's condition reveals the mother-karma. Strong 9th and 4th houses in the Dwadashamsha indicate significant dharmic inheritance from the parental lineage. This chart is particularly useful for understanding the depth of the Pitru (ancestral) karma operating in the native's life." },
      { heading: "D-60 Shashtiamsha — Pure Karma", body: "The Shashtiamsha is the most refined of all Vargas — dividing each sign into 60 parts of 0°30' each. It is considered to show the pure karma of the soul, independent of the circumstances of the current incarnation. Traditional Jyotishis gave the Shashtiamsha the highest weight in the Shadbala calculation. Its interpretation requires the most precise birth time (accurate to within minutes) and the deepest philosophical understanding. What is shown in the Shashtiamsha is karmic in the most fundamental sense — it points to the quality of consciousness that generated the current prarabdha." }
    ]
  },
  "muhurta": {
    sections: [
      { heading: "The Science of Auspicious Time", body: "Muhurta (also spelled Muhūrta) is the Jyotish science of electional astrology — the art and precision of selecting the most auspicious moment for important actions. Where natal Jyotish reads the karma of a birth moment, Muhurta selects a birth moment that will give a new enterprise, relationship, or undertaking the strongest possible cosmic foundation. The principle: every beginning has a chart, and the quality of that chart determines the quality of the thing begun." },
      { heading: "The Five Limbs of the Panchanga", body: "Muhurta analysis centers on the Panchanga (five limbs of the auspicious day): (1) Vara (weekday) — each day is ruled by a planet whose quality pervades all activity that day; (2) Tithi (lunar day) — the Moon's phase and distance from the Sun, cycling through 30 tithis monthly; (3) Nakshatra (lunar mansion occupied by Moon) — the quality of the Moon's current station; (4) Yoga (Sun-Moon combination) — 27 yogas created by the sum of Sun and Moon longitudes, ranging from highly auspicious to actively inauspicious; (5) Karana (half-tithi) — 11 karanas cycling through the month, each with specific qualities for specific actions. A Muhurta is considered strong when multiple Panchanga factors align auspiciously simultaneously." },
      { heading: "Hora — The Planetary Hour", body: "Each day is divided into 24 Horas (planetary hours) — not clock hours but proportional divisions of day and night. Each Hora is ruled by a planet in the sequence: Sun, Venus, Mercury, Moon, Saturn, Jupiter, Mars (repeating). The day's first Hora is always ruled by the day's planetary lord (Sunday begins with Sun Hora, Monday with Moon Hora, etc.). For time-sensitive actions — initiating a business call, signing a document, performing a ritual — the Hora provides a fine-grained additional layer of selection beyond the broader Muhurta." },
      { heading: "Inauspicious Times — What to Avoid", body: "As important as selecting auspicious times is avoiding the inauspicious ones. Rahu Kala (Rahu's period) falls on every day at a predictable time based on the weekday — approximately 90 minutes of Rahu's amplifying and shadow-creating influence. Gulika Kala (Saturn's son's period) is similarly avoided. Yamakantaka, Dundubhi Yoga, Visha Ghati — these are specific combinations to avoid for new beginnings. Most temples, traditional families, and Jyotishis automatically exclude these periods from any Muhurta consideration." },
      { heading: "Marriage Muhurta — The Most Complex Calculation", body: "Marriage Muhurta is considered the most important and complex Muhurta calculation because marriage is the most significant of all new beginnings — it creates a new karma that will unfold over a lifetime. Traditional considerations include: the Nakshatra of the bride and groom (certain combinations are incompatible for marriage Muhurta), the Tithi (certain tithis are actively inauspicious for marriage), Venus and Jupiter not being combust (critical for marriage Muhurta — combust Venus or Jupiter on a wedding day significantly affects the marriage's quality), the Lagna of the Muhurta chart (7th house should be free of malefics), and the Moon's position (should not be in the 8th from the Muhurta lagna)." },
      { heading: "The Metaphysical Principle", body: "Why does Muhurta work? The Vedic answer: because every beginning is a birth, and the birth chart of any beginning carries the same karmic weight as a human birth chart. The cosmos does not distinguish between the 'birth' of a corporation, a marriage, a building, or a child — every moment of inception creates a chart, and that chart's quality shapes the thing's entire lifecycle. Muhurta is the technology of choosing the best available birth chart for the things you are creating. It does not override the native's own karma — it works within it, selecting the most dharmically aligned window within what the native's karma makes possible." }
    ]
  },
  "karma-theory": {
    sections: [
      { heading: "Karma Beyond the Ledger Metaphor", body: "The popular conception of karma as a cosmic ledger — where good deeds deposit and bad deeds withdraw — is a useful simplification that ultimately misrepresents karma's actual nature. Karma is not a scoring system. It is a precise, impersonal record of the patterns of consciousness that have been active across incarnations. These patterns do not wait passively to be 'paid off.' They actively organize the field of experience — creating tendencies, attracting specific circumstances, and generating the prarabdha that shapes the current life." },
      { heading: "Sanchita — The Entire Accumulation", body: "Sanchita karma is the totality of accumulated karma from all past lives — literally 'that which has been heaped up.' It is vast beyond comprehension: every action, every intention, every pattern of consciousness from countless incarnations. The crucial insight: most Sanchita will never be experienced in any single lifetime. The cosmos does not attempt to 'clear the ledger' in a single incarnation — it selects, with extraordinary precision, exactly the karma that is ready to crystallize in the current conditions. The 8th house and its lord in the natal chart are the visible index of Sanchita in the current chart — showing where the hidden depths of accumulated karma are most active." },
      { heading: "Prarabdha — The Selected Karma", body: "Prarabdha karma is the portion of Sanchita selected for this lifetime — already crystallized, already inescapable, already in motion at birth. The birth chart is its precise map. The lagna shows how this karma is being experienced from the inside (the subjective dimension of prarabdha). The planets show which specific domains of karma are active. The dashas show when specific portions of prarabdha come into expression. Prarabdha cannot be 'burned away' through spiritual practice — it must be lived through. What spiritual practice can change is the quality of consciousness with which prarabdha is experienced, and therefore the agami karma generated in response to it." },
      { heading: "Agami — The Living Karma", body: "Agami karma is the karma being generated right now — through every choice, every response, every quality of attention brought to the present moment. This is the domain of genuine free will: not freedom from prarabdha, but freedom in how consciousness meets prarabdha. The quality of this response is itself a karmic action — it generates the seed of the next life's prarabdha. The native who meets Saturn's crystallization with patience, structural effort, and philosophical understanding generates agami karma of a specific quality. The native who meets the same Saturn with resentment, avoidance, or self-pity generates a different agami karma. Same prarabdha, completely different agami — and therefore different future prarabdha." },
      { heading: "Karma and the Houses", body: "Each house in the Jyotish chart corresponds to a specific domain of karma: The 5th house (Purva Punya Bhava) shows the accumulated merit from past lives available as grace in the current one — this is why a strong 5th house or its lord produces unexpected blessings that feel unearned. The 8th house shows the hidden karma requiring transformation — the domain where the deepest, most intractable patterns from Sanchita are most active. The 12th house shows the karma of loss and release — what must be surrendered in this lifetime to prevent its accumulation into the next Sanchita pool. Reading these three houses together reveals the karmic trajectory across lifetimes with unusual clarity." },
      { heading: "The Crystallization Model", body: "The most useful model for understanding how karma moves from Sanchita to Prarabdha to manifest event: the geological crystallization process. Karma accumulates as sediment (action and intention depositing over lifetimes). Under Kala-pressure (Saturn's function), it compresses from sediment to stone. Under sufficient compression, it crystallizes — becoming prarabdha: specific, structured, with a precise geometry. The dasha-transit nexus provides the final trigger: the snap from crystal-in-formation to crystal-manifest-in-Bhuloka. This model explains why karma cannot be rushed (crystallization requires the time it requires), why it cannot be forced (premature pressure shatters rather than crystallizes), and why it arrives with such apparent suddenness (the crystal snaps into form at the precise moment conditions are met)." }
    ]
  },
  "purusha-prakriti": {
    sections: [
      { heading: "The Foundation Beneath Jyotish", body: "Before there is astrology, before there are planets or houses or dashas, there is the fundamental metaphysical question that the Vedic tradition answers more precisely than any other system: what is the relationship between the witnessing consciousness and the field of experience it witnesses? The answer — Purusha and Prakriti — is the foundation beneath all of Jyotish. Without understanding it, the chart is merely a predictive tool. With it, the chart becomes a technology of liberation." },
      { heading: "Purusha — The Witness", body: "Purusha is the 25th tattva in the Samkhya enumeration — beyond all the others, prior to all manifest reality. It is pure, unmodified witnessing consciousness: it does not act, does not have karma, does not experience suffering or joy in the ordinary sense. It simply witnesses. The Purusha of the Samkhya is not a personal god — it is the principle of awareness itself, the 'light' in which all experience appears. Every individual has a Purusha — the deep witnessing presence that remains unchanged through every dasha, every transit, every life event. This is the consciousness that Jyotish's chart cannot map, because it is prior to all mapping." },
      { heading: "Prakriti — The Field", body: "Prakriti is the 24 tattvas — the entirety of manifest existence from the most subtle (Mahat, the cosmic intelligence) to the most gross (Prithvi, the earth element). Everything the chart maps is Prakriti: the planets are Prakriti, the karma is Prakriti, the dashas are Prakriti, the events of the life are Prakriti. Prakriti is not inferior to Purusha — it is the field in which Purusha's witnessing occurs. Without Prakriti, there is nothing to witness. Without Purusha, the witnessing of Prakriti would produce only mechanical responses with no possibility of recognition, understanding, or liberation." },
      { heading: "The Fundamental Confusion", body: "The root of all suffering in the Samkhya framework is Avidya — the confusion of Purusha with Prakriti. The witnessing consciousness mistakes itself for the field being witnessed. The 'I' (Ahamkara — the ego tattva, part of Prakriti) claims to be the Purusha. The result: the consciousness that is inherently free believes itself to be bound by karma, limited by circumstance, subject to the suffering that belongs only to Prakriti. Jyotish, at its deepest level, is a technology of distinguishing Purusha from Prakriti — by making Prakriti (the chart) extraordinarily explicit, it creates the conditions for Purusha (the observer of the chart) to recognize itself as distinct from what it is observing." },
      { heading: "The Kalapurusha — The Cosmic Body", body: "Vedic cosmology identifies a Kalapurusha (the Cosmic Being of Time) whose body IS the zodiac — whose head is Aries, whose face is Taurus, whose arms are Gemini, whose heart is Leo, whose abdomen is Virgo, and so on through Pisces at the feet. The birth chart is understood as the intersection of the individual's Prakriti-field with the Kalapurusha's cosmic body at the moment of incarnation. This is why specific body parts are associated with specific signs and houses — the connection is not arbitrary symbolism but a literal mapping of the individual microcosm onto the cosmic macrocosm." },
      { heading: "Practical Application in Reading", body: "The Purusha-Prakriti distinction has a specific practical application in chart reading: every planetary configuration maps a quality of Prakriti — a pattern of karma, a tendency in the field. The Jyotishi's task is to read these patterns with maximum precision. But the deeper task — the one that distinguishes a Jyotishi from a mere predictor — is to occasionally remind the client that they are not the chart. The cancer lagna, the Saturn in the 8th, the Venus Rx — these are configurations of Prakriti that the Purusha is witnessing in this incarnation. They are extraordinarily important maps of the current terrain. They are not the traveler." }
    ]
  },
  "kala-time": {
    sections: [
      { heading: "Two Kinds of Time", body: "The Vedic tradition distinguishes between two fundamentally different modes of time. Samaya is sequential, measurable time — the time of clocks, calendars, and event sequences. One moment follows another. This is the time of Mercury and the Sun: instrumental, communicable, shared. Kala is something altogether different. It is not a sequence but a depth — the accumulation of pressure that makes things inevitable before they become visible. Kala does not tick forward; it deepens downward. It is geological time, karmic time, the time in which prarabdha is crystallized from the raw material of Sanchita." },
      { heading: "Saturn as Kala Purusha", body: "Saturn's designation as Kala Purusha — the embodiment of cosmic time — is not metaphorical. Astronomically, Saturn moves at approximately 1 degree per 12 days, completing its zodiacal orbit in 29.5 years. This is the slowest motion of all the classical planets. The further a planet is from the radiant center (the Sun), the more deeply it operates in Kala rather than Samaya. Mercury, closest to the Sun, operates most in Samaya — quick, adaptive, immediately responsive. Saturn, furthest of the classical seven, operates most in Kala — slow, inevitable, geological. His slowness is not limitation but nature expressed cosmologically." },
      { heading: "The Maha Yugas — Kala at the Largest Scale", body: "The Maha Yuga cycle is Kala operating at its vastest scale — the 4,320,000-year cycle of cosmic ages. Satya Yuga (1,728,000 years): the Golden Age, full consciousness, direct human-divine connection. Treta Yuga (1,296,000 years): three-quarters conscious, ritual becomes necessary as the direct connection thins. Dvapara Yuga (864,000 years): half conscious, dharma and adharma in active balance. Kali Yuga (432,000 years): one-quarter conscious, the densest material experience, the thickest veil. We are currently approximately 5,125 years into Kali Yuga." },
      { heading: "Kali Yuga — The Accelerated Path", body: "Kali Yuga is simultaneously the most challenging and the most opportunity-rich of the four ages. The veil between Purusha and Prakriti is at maximum thickness — which makes the veil more difficult to pierce but makes any genuine piercing more powerful. In Satya Yuga, spiritual practice produces liberation naturally and relatively easily — but the accomplishment is less distinctive because the terrain supports it. In Kali Yuga, any genuine spiritual accomplishment occurs against maximum friction — and friction produces heat, and heat, properly directed, produces the tapas that purifies karma with extraordinary efficiency. The Kali Yuga practitioner who achieves genuine recognition of Purusha has accomplished in one lifetime what might take many in Satya Yuga." },
      { heading: "Dasha Time vs. Samaya Time", body: "The dasha system operates in a time-domain between Samaya and Kala. Dasha periods are not sequential events in Samaya — they are shifts in the quality of Kala-pressure bearing on the native's chart. When Saturn Mahadasha begins, it is not that Saturn has increased in strength or changed position — it is that the Kala-pressure of Saturn's function in the natal chart has become the dominant organizing principle of the native's entire field. Events still occur in Samaya; but their selection, their quality, and their ultimate meaning are now being organized by the Kala-function of Saturn." },
      { heading: "How to Work with Kala", body: "The practical teaching of Kala for the native in any challenging Saturn period: you cannot work in Samaya to solve a Kala problem. Effort, strategy, networking, and activity — these are Samaya tools. They are useful and necessary but insufficient. Kala responds to depth, not speed. What works in Kala: structural integrity (building what is genuinely solid rather than what appears solid), patient sustained effort over long periods (which is why Saturn rewards it), and the willingness to allow the crystallization process to complete on its own timeline rather than attempting to accelerate it. The native who understands Kala stops asking 'when will this end?' and starts asking 'what is this completing?'" }
    ]
  },
  "consciousness": {
    sections: [
      { heading: "The Limit of the Map", body: "Jyotish is the most precise map of Prakriti — the manifest field of karma and consciousness — ever developed by any tradition. The nava grahas, the 27 nakshatras, the 12 bhavas, the dashas, the yogas, the Ashtakavarga, the 16 divisional charts — together they constitute a cartographic achievement of extraordinary precision. And yet: no map includes the cartographer. The birth chart maps everything the natal consciousness encounters in the field. It cannot include the consciousness doing the encountering. This is not a failure of Jyotish — it is its highest teaching." },
      { heading: "The Observer Behind the Chart", body: "In every chart reading, there are two presences: the chart (Prakriti's map) and the one reading it (the Purusha witnessing its own Prakriti-field through the mediation of the Jyotishi). The Jyotishi's task is to read the chart with maximum precision — to map the karma with complete accuracy. The meta-task, which no chart can perform but every genuine Jyotishi holds in awareness, is to occasionally point the native toward the one for whom the chart exists. You are not Cancer lagna. You are the consciousness that chose Cancer lagna for the specific karmic work of this incarnation." },
      { heading: "Ajappa — The Breath That Remembers", body: "The Sikh tradition contributes a practice that formal Jyotish does not provide: Ajappa Jaap — the mantra that repeats itself in the rhythm of breath without requiring conscious initiation. Waheguru synchronized with the natural breath cycle. This is not supplementary to Jyotish — it is the practice that makes Jyotish sustainable. The chart tells you what Saturn is doing in the 8th house. Ajappa reminds you, breath by breath, what you are while Saturn is doing it. Without the practice, the chart can intensify identification with Prakriti. With the practice, the chart becomes a transparent map — fully visible, fully respected, but not confused with the territory." },
      { heading: "Three Levels of Chart Reading", body: "Level one: predictive. What events will occur and when? This is the most commonly sought level and is entirely legitimate. Jyotish can predict with remarkable precision. Level two: psychological. What patterns of consciousness are generating these events? What karma is being worked through? This level transforms prediction into understanding. Level three: liberational. What is the Purusha-Prakriti distinction that this specific chart is designed to make vivid? What recognition is this particular configuration of karma pointing toward? This level is what the ancient Rishis designed Jyotish for — not prediction, not even psychological understanding, but the recognition of the consciousness that is prior to all charts." },
      { heading: "When the Chart Has Completed Itself", body: "Every dasha period exhausts itself. Every transit passes. Every yoga activates or its window closes. The 120-year Vimshottari cycle completes, and if the native lives long enough, a new cycle begins. Eventually — across incarnations — all prarabdha karma is experienced and released. What remains when the chart has fully completed its work is what was always there: the Purusha that was never actually bound by any of it. Jyotish, understood completely, is a technology for accelerating this completion — for using the precise understanding of karma's structure to meet it with full consciousness rather than unconscious reaction, and thereby to generate agami karma of progressively lighter, more transparent quality, until the distinction between karma and its resolution becomes unnecessary." },
      { heading: "The Silence at the Center of Every Chart", body: "Shatabhisha's symbol is an empty circle: one hundred stars forming a ring around a void. This is the most precise symbol in all of Jyotish for what consciousness ultimately is — not the stars (the experiences, the karma, the chart) but the empty center around which they organize. Every chart has a silence at its center: the Purusha-witness for whom all the planetary drama arises. The Jyotishi who can occasionally glimpse this silence — in their own chart and in the charts they read — is practicing Jyotish at its highest frequency. Not prediction. Not even wisdom. Recognition." }
    ]
  },
  "brihat-parashara": {
    sections: [
      { heading: "The Foundation Text", body: "The Brihat Parashara Hora Shastra (BPHS) is the foundational text of Jyotish — a comprehensive compilation of astrological knowledge traditionally attributed to the sage Parashara, father of the great poet Vyasa. It is presented as a dialogue between Parashara and his disciple Maitreya, and covers virtually every dimension of Jyotish: grahas, rashi, bhavas, dashas, yogas, Ashtakavarga, divisional charts, muhurta, and remedies. Modern scholarship dates the current text to approximately the 7th-10th century CE, though it draws on knowledge far older." },
      { heading: "What Contemporary Practice Has Lost", body: "The BPHS contains approximately 100 chapters and 3,000+ shlokas (verses). Contemporary Jyotish practice, even among serious students, typically engages with perhaps 30% of this content. The most neglected sections include: the chapters on Sudarshana Chakra (reading the chart simultaneously from the lagna, Moon, and Sun); the Kalachakra Dasha system (considered more accurate than Vimshottari by some traditions); the detailed Ashtakavarga refinements including Trikona Shodhana and Ekadhipatya; the chapters on Nadi Jyotish techniques; and the chapters on the relationship between the birth chart and past-life karma patterns." },
      { heading: "The Cosmic Worldview of Parashara", body: "Before presenting any astrological technique, Parashara establishes the cosmic worldview within which Jyotish makes sense. He begins with the nature of Brahman, the incarnation of Vishnu's avatars into the planets, the relationship between the cosmic Purusha and the individual soul, and the mechanism by which karma flows from Sanchita to Prarabdha. This philosophical foundation is almost never taught in contemporary Jyotish education — students learn the techniques without the worldview that gives the techniques their meaning and their limits." },
      { heading: "The Planetary Avatars", body: "One of the most profound and least-discussed teachings of the BPHS: each of the nava grahas is an avatar (descent) of Vishnu into a specific cosmic function. The Sun is Rama — the ideal king, embodying perfect dharma. The Moon is Krishna — the beloved, embodying perfect relationship. Mars is Narasimha — the fierce protector. Mercury is the Buddha — discrimination and enlightenment. Jupiter is Vamana — expansion and cosmic grace. Venus is Parashurama — the warrior-sage, Shukra's tantric dimension. Saturn is Kurma — the tortoise, slow and foundational. Rahu is Varaha — the boar who dives into the depths. Ketu is Matsya — the fish, the first incarnation, the beginning and end of cycles." },
      { heading: "How to Study the BPHS", body: "The BPHS is not a textbook to be read linearly. It is a reference text to be studied in layers. The recommended approach for the serious student: first study with a living teacher who can provide the interpretive tradition (sampradaya) that makes the verses comprehensible. Second, read one section at a time — a single chapter, thoroughly, until its meaning becomes clear both intellectually and experientially. Third, apply every technique to actual charts before moving to the next technique. The verse that makes no sense theoretically often becomes crystalline when applied to five charts. Fourth, keep K.N. Rao's commentaries and Sanjay Rath's writings alongside the text — they represent two of the strongest living interpretive traditions." }
    ]
  },
  "remedies": {
    sections: [
      { heading: "What Remedies Actually Do", body: "The popular understanding of Jyotish remedies — wear a blue sapphire and Saturn will stop afflicting you — fundamentally misunderstands how remedies work. Remedies do not change the natal chart. They do not cancel karma. They do not prevent the crystallization that Kala has already set in motion. What remedies do: they change the quality of the native's relationship to the planetary energy — their resonance with it, their capacity to work with it rather than against it, and sometimes the specific expression it takes within the range of possibilities the karma allows." },
      { heading: "Gemstones — The Resonance Technology", body: "Each classical gemstone is associated with a specific planet and is believed to amplify that planet's energy through resonant transmission — the gemstone functioning as a biological antenna for the planetary frequency. Ruby for the Sun. Pearl for the Moon. Red coral for Mars. Emerald for Mercury. Yellow sapphire for Jupiter. Diamond for Venus. Blue sapphire for Saturn. Hessonite for Rahu. Cat's eye for Ketu. The critical rule: gemstones should only be worn for naturally benefic planets (Jupiter, Venus, Mercury, and sometimes Moon or Sun depending on the chart), or for the ruling planets (the lagna lord and other chart lords that are beneficial for the specific ascendant). Wearing a gemstone for a malefic — particularly Saturn or Rahu — amplifies that planet's malefic quality along with its benefits, which is often counterproductive." },
      { heading: "Mantras — The Sonic Technology", body: "Mantra is perhaps the most precisely calibrated of all remedies. Each planet has a Beeja (seed) mantra — a short, intense sound-formula that creates a specific resonance in the subtle body. Extended repetition (traditionally 108 times daily, or 18,000-125,000 repetitions over a dedicated period) creates sustained resonance with the planetary intelligence. The Navagraha Stotra (hymn to the nine planets), the planetary Gayatri mantras, and specific Beeja mantras each operate at different levels of subtlety. The most powerful planetary mantra practice is done at the Hora of the planet being propitiated, on the planet's day, and preferably during the planet's transit over auspicious Ashtakavarga positions in the natal chart." },
      { heading: "Charitable Acts — The Karmic Technology", body: "Dana (charitable giving) is among the most traditionally recommended remedies for difficult planetary periods. The principle: by voluntarily giving away the significations of the afflicting planet, the native creates agami karma that counteracts the afflicting karma. For Saturn afflictions: giving to the poor, serving the elderly and disabled, donating oil lamps on Saturday evenings. For Sun afflictions: giving wheat, copper, or red flowers on Sundays. For Mars afflictions: donating blood, giving red lentils, supporting veterans. The charitable act works not because it 'pays off' karma in a transactional sense, but because it reorients the native's consciousness toward the planetary principle's highest expression rather than its most constricted one." },
      { heading: "Fasting — The Discipline Technology", body: "Planetary fasting (Vrata) on the planet's weekday is a classical remedy for both strengthening a weak planet and moderating an excessive one. Moon fasting on Mondays: abstaining from salt, eating only white foods, maintaining emotional equilibrium. Saturn fasting on Saturdays: abstaining from salt and oil, performing service to those in need. The mechanism: voluntary discipline (Saturn's virtue) offered on Saturn's day creates a resonance between the native's will and Saturn's Kala function. This is not superstition — it is a sophisticated technology of using self-imposed limitation to align consciousness with the demanding but ultimately constructive quality of planetary intelligence." },
      { heading: "Yantras — The Geometric Technology", body: "A Yantra is a geometric diagram that encodes a specific planetary intelligence in visual form. The Shri Yantra encodes Lakshmi/Venus. The Kali Yantra encodes Ketu's liberation. Specific planetary yantras encode each of the nava grahas. Yantras are 'activated' through specific mantra repetition and ritual installation, after which they function as stable focal points for the planetary resonance in the native's living or working space. Where gemstones work through the physical body and mantras through the subtle body, yantras work through the spatial-environmental dimension — creating a field of planetary resonance in the space where the native spends significant time." }
    ]
  },
  "houses-deep": {
    sections: [
      { heading: "Beyond Keywords — The Metaphysical Function", body: "Standard Jyotish education teaches house significations as keyword lists: the 2nd house is wealth, speech, family. The 7th house is marriage, partnerships, trade. These are accurate but incomplete. The complete understanding of each bhava includes its metaphysical function — the specific type of consciousness-experience the house generates, its corresponding loka, its relationship to the karmic architecture of the life, and what becomes possible when the house is fully activated versus suppressed." },
      { heading: "The 1st House — The Lagna", body: "The Lagna is simultaneously the most personal and most cosmic point in the chart. It is where the individual meets the universal — the precise degree of the zodiac rising on the eastern horizon at the moment of birth, chosen (in the Vedic worldview) by the soul to provide the exact Prakriti-vehicle required for the current prarabdha. The lagna lord is the most important planet in the chart — its condition shapes everything. A strong lagna lord means the native has genuine capacity to activate whatever the chart contains. A weak lagna lord means the chart's potential remains largely latent." },
      { heading: "The 4th House — The Inner World", body: "The 4th house (Sukha Bhava — house of happiness) is not merely about mother, home, and property. It is the house of the inner sanctuary — the private, subjective world that the native inhabits below the threshold of public life. Whatever is in the 4th house colors the quality of inner experience regardless of external circumstances. A strong 4th house produces a native who carries genuine inner contentment — who can be in difficult external circumstances and remain fundamentally at peace. A damaged 4th house produces restlessness and the inability to find genuine rest, regardless of external comfort." },
      { heading: "The 5th House — Jana Loka's Window", body: "The 5th house (Purva Punya Bhava) is the window through which Jana Loka intelligence descends into the individual life. Purva Punya — the merit accumulated across previous lives — is stored here and releases as what appear to be unearned blessings, natural talents, and creative gifts. The native with a strong 5th house and its lord seems to receive things that others must work far harder to obtain. This is not injustice — it is the legitimate fruit of previous lifetimes' dharmic effort, now available as grace. The 5th house also governs the quality of consciousness that the native passes to children — the karmic transmission between generations." },
      { heading: "The 8th House — Patala's Domain", body: "The 8th house is the most feared in Jyotish and the most misunderstood. It is Patala's window — the point in the chart where the subterranean karma is most directly accessible. Its negative significations (death, sudden events, chronic illness, loss, hidden enemies) are all expressions of Patala's nature: what operates below the surface, what cannot be seen or controlled from Bhuloka. But the 8th house's positive significations (tantra, occult knowledge, transformational capacity, longevity, inheritance, research) are equally expressions of Patala: the extraordinary depth that becomes accessible when one is willing to descend below the surface. The native with a strong 8th house is not cursed — they are a Patala-capable consciousness: someone whose depth exceeds what Bhuloka can fully contain." },
      { heading: "The 12th House — The Portal", body: "The 12th house (Vyaya Bhava — house of expenditure) is the portal between Bhuloka and the higher lokas. Its significations of loss, foreign lands, hospitals, isolation, and spiritual practice all point to the same principle: the dissolution of the boundary between individual and universal. What is 'lost' in the 12th house is not gone — it is dissolved into something larger. Foreign lands represent the dissolution of local identity. Hospitals represent the dissolution of the body's illusion of permanence. Spiritual practice represents the voluntary dissolution of ego-boundary. The native with a strong 12th house is a Satya-Loka-aspiring consciousness: someone whose gravitational pull is toward the plane where individual boundaries dissolve into universal consciousness." }
    ]
  },
};

export default function EncyclopediaTopicPage({ params }: { params: { slug: string } }) {
  const topic = encyclopediaTopics.find(t => t.slug === params.slug);
  if (!topic) return notFound();
  const content = deepContent[params.slug];
  const idx = encyclopediaTopics.indexOf(topic);
  const prev = encyclopediaTopics[idx - 1];
  const next = encyclopediaTopics[idx + 1];

  return (<>
    <section style={{ minHeight: "55vh", display: "flex", flexDirection: "column", alignItems: "center", justifyContent: "center", textAlign: "center", padding: "140px 24px 80px" }}>
      <span style={{ fontFamily: "'Cinzel',serif", fontSize: ".58rem", letterSpacing: ".45em", color: "#6a5820", marginBottom: "16px", display: "block" }}>{topic.category.toUpperCase()} · ENCYCLOPEDIA</span>
      <h1 style={{ fontFamily: "'Cinzel Decorative',serif", fontSize: "clamp(2rem,6vw,4rem)", fontWeight: 700, color: "#f0d878", textShadow: "0 0 60px rgba(200,168,76,.2)", letterSpacing: ".04em", marginBottom: "28px", maxWidth: "800px" }}>{topic.title.toUpperCase()}</h1>
      <p style={{ maxWidth: "620px", fontSize: "1.1rem", fontStyle: "italic", color: "rgba(232,240,248,.62)", lineHeight: 1.9 }}>{topic.description}</p>
    </section>
    <GoldDivider />
    <section style={{ background: "linear-gradient(to bottom,#030810,#050d1a)", padding: "80px 0 120px" }}>
      <div style={{ maxWidth: "900px", margin: "0 auto", padding: "0 48px" }}>
        {content ? (
          <RevealSection>
            <ProseKala>
              {content.sections.map((s, i) => (
                <div key={i}>
                  <h3>{s.heading}</h3>
                  <p>{s.body}</p>
                </div>
              ))}
            </ProseKala>
          </RevealSection>
        ) : (
          <RevealSection>
            <ProseKala>
              <h3>Overview</h3>
              <p>{topic.description}</p>
              <p>This entry is being expanded with full encyclopedia-depth content. The knowledge here draws from the classical Jyotish tradition — particularly Brihat Parashara Hora Shastra, Brihat Jataka, Jataka Parijata, and the living traditions of K.N. Rao and Sanjay Rath — combined with original analysis not found elsewhere in Jyotish literature on the internet.</p>
              <blockquote>"Study the chart for a thousand hours and you will begin to see it. Study the consciousness that is reading the chart, and Jyotish will have served its highest purpose."<cite>— Traditional</cite></blockquote>
            </ProseKala>
          </RevealSection>
        )}

        <div style={{ marginTop: "60px", display: "flex", justifyContent: "space-between", borderTop: "1px solid rgba(255,255,255,.04)", paddingTop: "32px" }}>
          {prev ? <Link href={`/encyclopedia/${prev.slug}`} style={{ fontFamily: "'Cinzel',serif", fontSize: ".6rem", letterSpacing: ".18em", color: "#6a5820", textDecoration: "none" }}>← {prev.title}</Link> : <span />}
          {next ? <Link href={`/encyclopedia/${next.slug}`} style={{ fontFamily: "'Cinzel',serif", fontSize: ".6rem", letterSpacing: ".18em", color: "#6a5820", textDecoration: "none" }}>{next.title} →</Link> : <span />}
        </div>
      </div>
    </section>
  </>);
}
